"""
Curated augmentation data for internal-helpdesk intents.

This module contains carefully curated additional FAQ examples for intents
that have fewer than 10 examples in the base faq_dataset.csv.

All examples use the SAME company context already established in the
original faq_dataset.csv:
    - IT support:        extension 1234, it-support@company.com
    - HR:                extension 5678, hr@company.com
    - IT security:       extension 9999, security@company.com
    - Password portal:   portal.company.com (reset)
    - Webmail:           mail.company.com
    - Software portal:   software.company.com
    - IT helpdesk:       Building A, Room 101
    - HR office:         Building B, Room 201
    - Main office:       123 Business Park, Tech City

Every entry below follows the schema: (question, intent, answer, entity)
"""

# ---------------------------------------------------------------------------
# Attendance  (1 existing -> 12)
# ---------------------------------------------------------------------------
ATTENDANCE_AUGMENTED = [
    ("How do I mark my attendance each day?",
     "attendance",
     "Use the biometric scanner or the HR mobile app to clock in and out. Your attendance is recorded automatically.",
     "attendance"),
    ("Can I view my attendance on the mobile app?",
     "attendance",
     "Yes, download the HR mobile app and go to the Attendance tab. You can view daily, weekly, and monthly records.",
     "attendance"),
    ("What should I do if the attendance system is down?",
     "attendance",
     "Note your clock-in and clock-out times in a manual register and submit it to HR. The system will sync once it is back up.",
     "attendance"),
    ("How do I correct an incorrect attendance entry?",
     "attendance",
     "Submit a correction request through the HR portal within 24 hours. Your manager must approve the change.",
     "attendance"),
    ("Is there a grace period for clocking in?",
     "attendance",
     "A 10-minute grace period is allowed for clocking in each morning. Repeated late entries beyond the grace period will be flagged.",
     "attendance"),
    ("How do I check my overtime hours?",
     "attendance",
     "Overtime hours appear in the Attendance section of the HR portal. They are calculated based on your scheduled daily hours.",
     "attendance"),
    ("Can my manager view my attendance records?",
     "attendance",
     "Yes, managers can view team attendance in the HR portal under Reports > Attendance. They can also approve or reject correction requests.",
     "attendance"),
    ("What happens if I forget to clock out?",
     "attendance",
     "If you forget to clock out, contact HR at extension 5678 within the same day. The system will use your scheduled shift end time.",
     "attendance"),
    ("How do I generate an attendance report?",
     "attendance",
     "Go to HR Portal > Attendance > Reports. Select the date range and download the report as PDF or Excel.",
     "attendance"),
    ("Do part-time employees have different attendance rules?",
     "attendance",
     "Part-time employees follow a separate schedule set by their manager. Attendance is still tracked through the HR portal and mobile app.",
     "attendance"),
    ("How do I set up attendance notifications?",
     "attendance",
     "Enable notifications in the HR mobile app under Settings > Attendance. You will receive daily reminders to clock in and out.",
     "attendance"),
]
# ---------------------------------------------------------------------------
# Contact Information  (1 existing -> 12)
# ---------------------------------------------------------------------------
CONTACT_INFORMATION_AUGMENTED = [
    ("What is the IT helpdesk email address?",
     "contact_information",
     "Email IT support at it-support@company.com for non-urgent issues. For immediate assistance, call extension 1234.",
     "contact"),
    ("Where can I find the company directory?",
     "contact_information",
     "The company directory is on the company intranet under the Directory section. Search by name, department, or role to find contact details.",
     "contact"),
    ("What is the general company contact number?",
     "contact_information",
     "Call the main reception in the Building A lobby. Reception is available from 8 AM to 8 PM on weekdays.",
     "contact"),
    ("How do I contact the security desk?",
     "contact_information",
     "Reach the security desk at extension 9999 or security@company.com. The desk is in the main lobby of Building A.",
     "contact"),
    ("How do I find a specific colleague's contact details?",
     "contact_information",
     "Use the company directory on the company intranet. Search by name or employee ID to find their email and extension.",
     "contact"),
    ("How can I contact HR for general inquiries?",
     "contact_information",
     "Contact HR at extension 5678 or hr@company.com. The HR office is in Building B, Room 201.",
     "contact"),
    ("What is the best way to report an IT issue?",
     "contact_information",
     "Submit a ticket through the IT portal or call IT support at extension 1234. Email it-support@company.com for non-urgent issues.",
     "contact"),
    ("Can I message my manager through the company platform?",
     "contact_information",
     "Yes, use the company communication platform to message your manager. Their profile is also listed in the company directory on the intranet.",
     "contact"),
    ("Who should I contact for payroll questions?",
     "contact_information",
     "Direct payroll inquiries to HR at extension 5678 or hr@company.com. They will route your request to the payroll team.",
     "contact"),
    ("What are the emergency contact numbers?",
     "contact_information",
     "For emergencies, contact security at extension 9999. For medical emergencies, call 911. HR is at extension 5678 for urgent matters.",
     "contact"),
    ("How do I contact IT security?",
     "contact_information",
     "Contact IT security at extension 9999 or security@company.com for any security-related concerns.",
     "contact"),
]
# ---------------------------------------------------------------------------
# Employee ID  (1 existing -> 12)
# ---------------------------------------------------------------------------
EMPLOYEE_ID_AUGMENTED = [
    ("Where can I find my employee ID on my payslip?",
     "employee_id",
     "Your employee ID appears at the top right corner of your payslip in the HR portal. It starts with 'EMP-' followed by 5 digits.",
     "employee_id"),
    ("I lost my employee ID card. What should I do?",
     "employee_id",
     "Report the lost card to HR at extension 5678 immediately. A replacement card costs $10 and is ready in 3 business days.",
     "employee_id"),
    ("How do I request a replacement employee ID card?",
     "employee_id",
     "Submit a request through the HR portal under My Account > ID Card. Pick up your card from the HR office in Building B, Room 201.",
     "employee_id"),
    ("What if I forget my employee ID number?",
     "employee_id",
     "Your employee ID is listed in the HR portal under My Profile. You can also find it on your offer letter and pay stubs.",
     "employee_id"),
    ("How do I activate my employee ID card for building access?",
     "employee_id",
     "Visit the security desk in the Building A lobby with your ID card and employee ID number. Security will activate your card for building access.",
     "employee_id"),
    ("Can I use my employee ID for cafeteria payments?",
     "employee_id",
     "Yes, link your employee ID to your cafeteria account through the HR portal under My Account > Cafeteria. Payroll deduction is set up automatically.",
     "employee_id"),
    ("What is the format of my employee ID?",
     "employee_id",
     "Your employee ID follows the format EMP-XXXXX where X is a digit. It is unique to you and never changes.",
     "employee_id"),
    ("How do I update a name change on my employee ID?",
     "employee_id",
     "Submit a name change request through the HR portal with supporting documents. HR will issue a new employee ID card.",
     "employee_id"),
    ("Where do I collect my employee ID card?",
     "employee_id",
     "Collect your employee ID card from the HR office in Building B, Room 201. Bring a government-issued photo ID for verification.",
     "employee_id"),
    ("Can a temporary contractor get an employee ID?",
     "employee_id",
     "Contractors receive a vendor ID card instead of an employee ID. Contact HR at extension 5678 for details.",
     "employee_id"),
    ("How do I reset my employee ID account password?",
     "employee_id",
     "Employee ID account passwords are managed through the HR portal. Use the Forgot Password link under My Account.",
     "employee_id"),
]
# ---------------------------------------------------------------------------
# Holidays  (1 existing -> 12)
# ---------------------------------------------------------------------------
HOLIDAYS_AUGMENTED = [
    ("How do I check the company holiday calendar?",
     "holidays",
     "The holiday calendar is on the company intranet under HR > Holidays. It is updated annually with all official company holidays.",
     "holiday"),
    ("Is Independence Day a company holiday?",
     "holidays",
     "Yes, Independence Day is a company holiday. Check the intranet calendar under HR > Holidays for the exact date each year.",
     "holiday"),
    ("Are there any holidays in December?",
     "holidays",
     "Major December holidays include Christmas Day and New Year's Day. The full list is on the company intranet under HR > Holidays.",
     "holiday"),
    ("How many paid holidays does the company provide?",
     "holidays",
     "The company provides 10 paid holidays per year. The complete list is available on the company intranet under HR > Holidays.",
     "holiday"),
    ("Will salary be affected if payday falls on a holiday?",
     "holidays",
     "Salary is paid on the last working day of the month. If payday falls on a weekend or holiday, salary is credited on the previous working day.",
     "holiday"),
    ("Is New Year's Day a paid holiday?",
     "holidays",
     "Yes, New Year's Day is a paid company holiday. It is listed on the company holiday calendar in the HR portal.",
     "holiday"),
    ("Are there any half-day holidays?",
     "holidays",
     "No half-day holidays are observed. All holidays are full days off. Check the calendar on the company intranet for the full list.",
     "holiday"),
    ("Can I work on a company holiday for extra pay?",
     "holidays",
     "Working on a company holiday is discouraged and requires prior manager approval. Holiday work is compensated at 1.5x the regular rate.",
     "holiday"),
    ("How do I find the list of upcoming holidays?",
     "holidays",
     "Access the company holiday list on the company intranet under HR > Holidays. The calendar shows all upcoming holidays for the current year.",
     "holiday"),
    ("Do I get paid if I work during a holiday?",
     "holidays",
     "If you work on a company holiday with prior approval, you receive holiday pay plus 1.5x your regular hourly rate for the hours worked.",
     "holiday"),
    ("Is Labor Day a paid company holiday?",
     "holidays",
     "Yes, Labor Day is a paid company holiday. It is listed on the company holiday calendar under HR > Holidays on the company intranet.",
     "holiday"),
]
# ---------------------------------------------------------------------------
# HR Support  (1 existing -> 12)
# ---------------------------------------------------------------------------
HR_SUPPORT_AUGMENTED = [
    ("How do I submit an HR case?",
     "hr_support",
     "Submit an HR case through the HR portal under Support > New Case. Select the category and provide details for a prompt response.",
     "hr"),
    ("What are HR office hours?",
     "hr_support",
     "HR office hours are 9:00 AM to 6:00 PM, Monday to Friday. The office is in Building B, Room 201.",
     "hr"),
    ("How do I schedule an appointment with HR?",
     "hr_support",
     "Book an appointment through the HR portal under Support > Schedule Meeting. Walk-ins are also accepted during office hours.",
     "hr"),
    ("Can I request an employment verification letter?",
     "hr_support",
     "Request an employment verification letter through the HR portal under Services > Documents. It is issued within 2 business days.",
     "hr"),
    ("How do I update my personal information in HR records?",
     "hr_support",
     "Update your personal information through the HR portal under My Account > Profile. Some changes require supporting documents.",
     "hr"),
    ("How do I report a workplace concern to HR?",
     "hr_support",
     "Report workplace concerns through the HR portal under Support > Report Issue or call extension 5678. All reports are confidential.",
     "hr"),
    ("Can HR help with career counseling?",
     "hr_support",
     "Yes, HR offers career counseling sessions. Book through the HR portal under Development > Career Counseling. Sessions are free and confidential.",
     "hr"),
    ("How do I request a reference letter from HR?",
     "hr_support",
     "Submit a request through the HR portal under Services > Documents > Reference Letter. It is issued within 2 business days.",
     "hr"),
    ("What benefits does HR manage?",
     "hr_support",
     "HR manages health insurance, retirement plans, employee discounts, and wellness programs. Visit the HR portal under Benefits for full details.",
     "hr"),
    ("How do I file a formal complaint with HR?",
     "hr_support",
     "File a formal complaint through the HR portal under Support > Report Issue. All complaints are investigated confidentially.",
     "hr"),
    ("How do I enroll in company benefits?",
     "hr_support",
     "Benefits enrollment is done during onboarding. For changes, use the HR portal under Benefits > Enroll. Deadlines follow the annual open enrollment period.",
     "hr"),
]
# ---------------------------------------------------------------------------
# Internet Problems  (1 existing -> 12)
# ---------------------------------------------------------------------------
INTERNET_PROBLEMS_AUGMENTED = [
    ("My internet connection is very slow today.",
     "internet_problems",
     "Check if other devices are affected. Try restarting your router. If the issue persists, contact IT support at extension 1234.",
     "internet"),
    ("The internet is completely down in my office.",
     "internet_problems",
     "Check with colleagues to confirm the outage. Try restarting your router. If the outage is widespread, contact IT support at extension 1234.",
     "internet"),
    ("How do I reset my network settings?",
     "internet_problems",
     "Go to Control Panel > Network and Sharing Center > Change adapter settings. Right-click your connection and select Repair. If issues remain, call extension 1234.",
     "internet"),
    ("My ethernet cable is not working.",
     "internet_problems",
     "Check that the cable is firmly connected at both ends. Try a different port on the network switch. If it still fails, contact IT support at extension 1234.",
     "internet"),
    ("Why can I not access certain websites?",
     "internet_problems",
     "Some sites may be blocked by company security policy. If you need access for work, submit a request to IT support at extension 1234.",
     "internet"),
    ("The WiFi works on my phone but not on my laptop.",
     "internet_problems",
     "Check your laptop's WiFi settings. Ensure you are connected to the correct SSID. Restart your laptop and try again, or call extension 1234.",
     "internet"),
    ("My browser shows a DNS server not found error.",
     "internet_problems",
     "Try flushing your DNS cache by running 'ipconfig /flushdns' in Command Prompt. If the error persists, contact IT support at extension 1234.",
     "internet"),
    ("The network keeps disconnecting every few minutes.",
     "internet_problems",
     "Move closer to the WiFi router. Check if the issue is with a specific device. If it continues, contact IT support at extension 1234.",
     "internet"),
    ("Can I get a wired ethernet connection?",
     "internet_problems",
     "Ethernet cables are available from the IT helpdesk in Building A, Room 101. Contact IT support at extension 1234 to request one.",
     "internet"),
    ("My VPN connection drops after 30 minutes.",
     "internet_problems",
     "VPN sessions time out after 30 minutes of inactivity. Reconnect through the VPN portal at portal.company.com. If issues persist, call extension 1234.",
     "internet"),
    ("How do I test my internet speed?",
     "internet_problems",
     "Run the network diagnostics tool from the IT portal. For consistently slow speeds, contact IT support at extension 1234.",
     "internet"),
]
# ---------------------------------------------------------------------------
# Office Location  (1 existing -> 12)
# ---------------------------------------------------------------------------
OFFICE_LOCATION_AUGMENTED = [
    ("Where is the nearest coffee station?",
     "office_location",
     "Coffee stations are in the break rooms on every floor. The main one is in the kitchen area near Building A, Room 105.",
     "location"),
    ("Where is the main cafeteria?",
     "office_location",
     "The main cafeteria is on the ground floor of Building A. It is open from 8 AM to 4 PM on weekdays.",
     "location"),
    ("How do I get to Building B?",
     "office_location",
     "Building B is across the courtyard from Building A. Walk through the main lobby and follow signs to Building B. It houses HR and Finance.",
     "location"),
    ("Where is the nearest restroom?",
     "office_location",
     "Restrooms are located on every floor near the elevators. Gender-neutral restrooms are available on each floor as well.",
     "location"),
    ("Where can I find a quiet workspace?",
     "office_location",
     "Quiet workspaces are in the library zone on the 3rd floor of Building A. These areas enforce no phone calls or meetings.",
     "location"),
    ("Where is the nearest emergency exit?",
     "office_location",
     "Emergency exits are marked with green signs. The nearest exit from most desks is at the end of the hallway near the stairwell.",
     "location"),
    ("Where is the first aid station?",
     "office_location",
     "First aid stations are in the main lobbies of Building A and Building B. Trained first aiders are available on each floor.",
     "location"),
    ("Where can I find bookable meeting rooms?",
     "office_location",
     "Bookable meeting rooms are listed on the company intranet under Facilities > Meeting Rooms. Conference Room A seats 10 people.",
     "location"),
    ("How do I find a specific conference room?",
     "office_location",
     "Conference rooms are numbered and labeled on each floor. The room directory is on the company intranet under Facilities > Meeting Rooms.",
     "location"),
    ("Where is the employee parking lot?",
     "office_location",
     "Employee parking is in the lot behind Building A. Display your parking permit on the dashboard. Visitor parking is in the front lot.",
     "location"),
    ("Where is the fire assembly point?",
     "office_location",
     "The fire assembly point is in the courtyard between Building A and Building B. Proceed there immediately during a fire alarm or drill.",
     "location"),
]
# ---------------------------------------------------------------------------
# Payroll  (2 existing -> 12)
# ---------------------------------------------------------------------------
PAYROLL_AUGMENTED = [
    ("What documents are needed for salary processing?",
     "payroll",
     "Submit your bank details, PAN card, and PF UAN through the HR portal under My Account > Bank Details. Incomplete forms delay salary processing.",
     "payroll"),
    ("Who do I contact about a salary discrepancy?",
     "payroll",
     "Contact the payroll team through HR at extension 5678 or hr@company.com. Provide your employee ID and the payslip with the discrepancy.",
     "payroll"),
    ("How do I update my bank account for salary credit?",
     "payroll",
     "Submit a bank detail update form through the HR portal under My Account > Bank Details. Changes take effect from the next pay cycle.",
     "payroll"),
    ("What is the salary payment date each month?",
     "payroll",
     "Salary is credited on the last working day of each month. If the date falls on a weekend or holiday, salary is processed on the previous working day.",
     "payroll"),
    ("How do I request a salary advance?",
     "payroll",
     "Submit a salary advance request through the HR portal under Services > Payments. Approval requires manager and HR sign-off.",
     "payroll"),
    ("What deductions appear on my payslip?",
     "payroll",
     "Common deductions include income tax, PF, medical insurance, and professional tax. The detailed breakdown is in your payslip PDF.",
     "payroll"),
    ("Can I have my salary paid to a different bank account?",
     "payroll",
     "Yes, update your bank details in the HR portal under My Account > Bank Details. You may need to submit a voided cheque as proof.",
     "payroll"),
    ("How do I request an income certificate?",
     "payroll",
     "Request an income certificate through the HR portal under Services > Documents. It is issued within 2 business days.",
     "payroll"),
    ("What is the salary reimbursement procedure?",
     "payroll",
     "Submit expense reports with receipts through the HR portal under Services > Reimbursements. Reimbursements are processed with your next salary.",
     "payroll"),
    ("How do I check my salary credit status?",
     "payroll",
     "Your salary credit status is shown in the HR portal under My Account > Payslips. The status updates to Credited once processed.",
     "payroll"),
]
# ---------------------------------------------------------------------------
# Salary Information  (2 existing -> 12)
# ---------------------------------------------------------------------------
SALARY_INFORMATION_AUGMENTED = [
    ("Where can I view my salary structure?",
     "salary_information",
     "Your salary structure is in the HR portal under My Account > Salary. It shows your basic pay, allowances, and deductions.",
     "salary"),
    ("How is my monthly salary calculated?",
     "salary_information",
     "Your salary is calculated as basic pay plus allowances minus deductions. The detailed breakdown is in your payslip PDF.",
     "salary"),
    ("Can I see the salary breakup online?",
     "salary_information",
     "Yes, the complete salary breakup is available in the HR portal under My Account > Payslips. Download the PDF for full details.",
     "salary"),
    ("What components make up my monthly salary?",
     "salary_information",
     "Your salary includes basic pay, house rent allowance, conveyance, and bonuses minus tax and statutory deductions. See your payslip for details.",
     "salary"),
    ("How do I download my salary statement?",
     "salary_information",
     "Download salary statements from the HR portal under My Account > Payslips. Statements are available for the past 24 months.",
     "salary"),
    ("Why is my salary lower than expected?",
     "salary_information",
     "Check if there are new deductions or tax changes. Contact payroll through HR at extension 5678 with your employee ID for clarification.",
     "salary"),
    ("How do I view my past salary details?",
     "salary_information",
     "Access past salary details in the HR portal under My Account > Payslips. Select the month and year to view the payslip PDF.",
     "salary"),
    ("What is the salary revision policy?",
     "salary_information",
     "Salary revisions are reviewed annually based on performance and market benchmarks. Discussions happen during the appraisal cycle.",
     "salary"),
    ("How do I request a salary certificate?",
     "salary_information",
     "Request a salary certificate through the HR portal under Services > Documents. It is issued within 2 business days.",
     "salary"),
    ("How do I know if my salary has been credited?",
     "salary_information",
     "Salary credit status appears in the HR portal under My Account > Payslips. You will also receive an email notification when salary is credited.",
     "salary"),
]
# ---------------------------------------------------------------------------
# Security  (1 existing -> 12)
# ---------------------------------------------------------------------------
SECURITY_AUGMENTED = [
    ("How do I report a lost ID badge?",
     "security",
     "Report a lost ID badge immediately to the security desk at extension 9999. A replacement costs $10 and is ready in 2 business days.",
     "security"),
    ("How do I get after-hours access to the building?",
     "security",
     "Submit an after-hours access request through the HR portal under Services > Access. Security approves and sends a one-time access code.",
     "security"),
    ("What should I do if I see suspicious activity?",
     "security",
     "Immediately notify security at extension 9999 or security@company.com. Do not approach the individual. Provide details of the suspicious activity.",
     "security"),
    ("How do I update my security questions for login?",
     "security",
     "Go to Settings > Security > Security Questions in the employee portal. Update your questions and answers for account recovery.",
     "security"),
    ("What is the password change frequency policy?",
     "security",
     "Company policy requires password changes every 90 days. You will receive an email reminder 7 days before expiration.",
     "security"),
    ("What is multi-factor authentication?",
     "security",
     "Multi-factor authentication adds a second layer of security to your account. Enable it in Settings > Security > Two-Factor Authentication in the employee portal.",
     "security"),
    ("How do I secure my workstation when I leave?",
     "security",
     "Lock your computer with Ctrl+Alt+Delete or Windows+L. Report any unattended devices to security@company.com.",
     "security"),
    ("What should I do if I clicked a phishing link?",
     "security",
     "Immediately change your password and report the incident to IT security at extension 9999. Do not enter any further sensitive information.",
     "security"),
    ("What is the procedure for a lost or stolen laptop?",
     "security",
     "Report a lost or stolen laptop to IT security at extension 9999 within 2 hours. The device will be remotely wiped and the incident documented.",
     "security"),
    ("How do I encrypt sensitive files?",
     "security",
     "Use the built-in encryption tool in the employee portal under Services > Security > File Encryption. Contact IT security at extension 9999 for help.",
     "security"),
    ("What is the company's physical security policy?",
     "security",
     "All visitors must sign in at the front desk and wear a visitor badge. Employees must escort visitors at all times. Report violations to security at extension 9999.",
     "security"),
]
# ---------------------------------------------------------------------------
# Technical Support  (1 existing -> 12)
# ---------------------------------------------------------------------------
TECHNICAL_SUPPORT_AUGMENTED = [
    ("My laptop is running very slowly.",
     "technical_support",
     "Close unnecessary applications and restart your laptop. If it is still slow, check for updates in the IT portal. Contact IT support at extension 1234.",
     "it_support"),
    ("How do I connect a second monitor to my laptop?",
     "technical_support",
     "Connect the HDMI or VGA cable to your laptop and monitor. Extend or duplicate the display in Display Settings. Call extension 1234 if issues persist.",
     "it_support"),
    ("My laptop battery is draining too quickly.",
     "technical_support",
     "Check battery usage in Settings > System > Power. Reduce screen brightness and close background apps. If the battery is faulty, contact IT at extension 1234.",
     "it_support"),
    ("How do I back up my files automatically?",
     "technical_support",
     "The company backup agent runs daily in the background. For manual backup, use the backup tool in the IT portal. Contact IT support at extension 1234 for setup help.",
     "it_support"),
    ("My laptop screen is flickering intermittently.",
     "technical_support",
     "Update your graphics drivers through the IT portal. Check that the display cable is secure. If it persists, contact IT support at extension 1234.",
     "it_support"),
    ("How do I run system diagnostics on my laptop?",
     "technical_support",
     "Run the built-in diagnostics tool from the IT portal under Tools > Diagnostics. Or access it through Settings > Update and Security > Troubleshoot.",
     "it_support"),
    ("My laptop overheats during heavy use.",
     "technical_support",
     "Clean the air vents and ensure proper ventilation. Use a laptop stand. If overheating continues, contact IT support at extension 1234 for repair.",
     "it_support"),
    ("How do I reset my Outlook email profile?",
     "technical_support",
     "Go to Control Panel > Mail > Show Profiles. Create a new profile with your company email. Contact IT support at extension 1234 if needed.",
     "it_support"),
    ("My laptop will not power on.",
     "technical_support",
     "Check the power cable and battery. Try a hard reset by holding the power button for 15 seconds. If it still will not start, contact IT support at extension 1234.",
     "it_support"),
    ("How do I free up disk space on my laptop?",
     "technical_support",
     "Run Disk Cleanup from the Start menu. Delete temporary files and empty the recycle bin. Contact IT support at extension 1234 for assistance.",
     "it_support"),
    ("How do I update my laptop drivers?",
     "technical_support",
     "Download drivers from the company software portal at software.company.com or use Windows Update. Contact IT support at extension 1234 for help.",
     "it_support"),
]
# ---------------------------------------------------------------------------
# Working Hours  (1 existing -> 12)
# ---------------------------------------------------------------------------
WORKING_HOURS_AUGMENTED = [
    ("Can I work from home on Fridays?",
     "working_hours",
     "Remote work on Fridays is allowed with manager approval. Submit a remote work request through the HR portal at least 2 days in advance.",
     "working_hours"),
    ("What are the standard working hours?",
     "working_hours",
     "Standard working hours are 9:00 AM to 6:00 PM, Monday to Friday. Lunch break is from 1 PM to 2 PM.",
     "working_hours"),
    ("How do I request a shift change?",
     "working_hours",
     "Submit a shift change request through the HR portal under My Account > Schedule. Manager approval is required for all shift changes.",
     "working_hours"),
    ("Can I work late and leave early on another day?",
     "working_hours",
     "Flexible scheduling is available with manager approval. Submit a time change request through the HR portal with justification.",
     "working_hours"),
    ("What is the lunch break policy?",
     "working_hours",
     "The lunch break is from 1 PM to 2 PM daily. It is unpaid unless you are on a flexible schedule approved by your manager.",
     "working_hours"),
    ("How many hours should I work per week?",
     "working_hours",
     "The standard work week is 40 hours, Monday to Friday. Overtime beyond 45 hours requires prior manager approval.",
     "working_hours"),
    ("Can I work on weekends?",
     "working_hours",
     "Weekend work requires prior approval from your manager and HR. Weekend hours are compensated at 1.5x the regular rate.",
     "working_hours"),
    ("What is the overtime policy?",
     "working_hours",
     "Overtime is paid at 1.5x for hours beyond 45 per week. Submit overtime requests through the HR portal with manager approval.",
     "working_hours"),
    ("How do I report my working hours for remote days?",
     "working_hours",
     "Log your working hours in the HR portal under My Account > Attendance. Include your start, end, and break times for each day.",
     "working_hours"),
    ("What is the half-day policy?",
     "working_hours",
     "Half-day leave is allowed for personal matters. Apply at least 2 hours in advance through the HR portal under My Account > Leave.",
     "working_hours"),
    ("How do I find out if the office is closed during a holiday?",
     "working_hours",
     "Check the company calendar on the intranet under HR > Holidays. If a holiday is declared, the office is closed and remote work is optional.",
     "working_hours"),
]
# ---------------------------------------------------------------------------
# WiFi Problems  (11 existing -> 12)
# ---------------------------------------------------------------------------
WIFI_PROBLEMS_AUGMENTED = [
    ("How do I find the company WiFi network name?",
     "wifi_problems",
     "The company WiFi network name (SSID) is 'Company-Secure' for employees and 'Company-Guest' for visitors. Contact IT support at extension 1234 for passwords.",
     "wifi"),
]

# ---------------------------------------------------------------------------
# Greetings  (10 existing -> 12)
# ---------------------------------------------------------------------------
GREETINGS_AUGMENTED = [
    ("Hey there",
     "greetings",
     "Hello! How can I help you today? I can assist with IT issues, HR policies, and company questions.",
     "greeting"),
    ("Hi, how are you?",
     "greetings",
     "I'm doing well, thank you! How can I help you today with IT, HR, or any other company questions?",
     "greeting"),
]

# ---------------------------------------------------------------------------
# Goodbye  (10 existing -> 12)
# ---------------------------------------------------------------------------
GOODBYE_AUGMENTED = [
    ("I'm done asking questions",
     "goodbye",
     "Alright! If you need anything else, just ask. Have a great day ahead!",
     "goodbye"),
    ("That's everything I needed",
     "goodbye",
     "You're welcome! If you have more questions later, don't hesitate to ask. Goodbye!",
     "goodbye"),
]

# ---------------------------------------------------------------------------
# Master list — concatenated for easy import
# ---------------------------------------------------------------------------
AUGMENTED_DATA = (
    ATTENDANCE_AUGMENTED
    + CONTACT_INFORMATION_AUGMENTED
    + EMPLOYEE_ID_AUGMENTED
    + HOLIDAYS_AUGMENTED
    + HR_SUPPORT_AUGMENTED
    + INTERNET_PROBLEMS_AUGMENTED
    + OFFICE_LOCATION_AUGMENTED
    + PAYROLL_AUGMENTED
    + SALARY_INFORMATION_AUGMENTED
    + SECURITY_AUGMENTED
    + TECHNICAL_SUPPORT_AUGMENTED
    + WORKING_HOURS_AUGMENTED
    + WIFI_PROBLEMS_AUGMENTED
    + GREETINGS_AUGMENTED
    + GOODBYE_AUGMENTED
)
