#!/usr/bin/env python3
"""Generate the Module 2 Data Preprocessing notebook programmatically.

This script builds ``notebooks/data_preprocessing.ipynb`` for the
AI Based Fake News Detection Tool. The notebook covers ONLY data
preprocessing: loading, labelling, merging, cleaning, tokenization,
stopword removal, lemmatization, feature engineering, saving, and
reporting. No EDA / model training is included (later modules).

Usage:
    python notebooks/write_preprocessing_notebook.py
"""

import json
from pathlib import Path

# ----------------------------------------------------------------------
# Notebook builders
# ----------------------------------------------------------------------


def cell_code(source_lines: list[str]) -> dict:
    """Create a code cell from a list of source lines."""
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [s + "\n" for s in source_lines],
    }


def cell_md(source_lines: list[str]) -> dict:
    """Create a markdown cell from a list of source lines."""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [s + "\n" for s in source_lines],
    }


def make_notebook(cells: list[dict]) -> dict:
    """Assemble a Jupyter notebook JSON document."""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.12.0",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 4,
    }


# ----------------------------------------------------------------------
# Notebook cells
# ----------------------------------------------------------------------

cells = [
    # ==================================================================
    # STEP 1 — Project Introduction
    # ==================================================================
    cell_md([
        "# AI Based Fake News Detection Tool",
        "",
        "## Module 2 — Data Preprocessing",
        "",
        "### CodeVedX AI/ML Internship — Project 3",
        "",
        "---",
        "",
        "## 📌 Purpose",
        "",
        "This notebook performs the **complete data preprocessing pipeline**",
        "for the Fake News Detection project. It merges the raw `Fake.csv` and",
        "`True.csv` articles into a single, clean, machine-learning-ready",
        "dataset by:",
        "",
        "- Loading and inspecting both raw datasets.",
        "- Assigning binary labels (`Fake` → `0`, `True` → `1`).",
        "- Merging, shuffling, and resetting the index.",
        "- Cleaning the article text with a reusable NLP pipeline.",
        "- Tokenizing, removing stopwords, and lemmatizing.",
        "- Engineering additional NLP features.",
        "- Saving the processed dataset and a preprocessing report.",
        "",
        "## 🗂️ Dataset",
        "",
        "| File       | Description            | Rows (approx) |",
        "|------------|------------------------|---------------|",
        "| `Fake.csv` | Fake news articles     | ~23,481       |",
        "| `True.csv` | Real news articles     | ~21,417       |",
        "",
        "Both files share the columns: **`title`**, **`text`**, **`subject`**, and **`date`**.",
        "",
        "## 🔄 Workflow",
        "",
        "1. Import libraries and configure the environment.",
        "2. Download required NLTK resources automatically.",
        "3. Load and inspect `Fake.csv` and `True.csv`.",
        "4. Assign labels and merge into one dataset.",
        "5. Handle missing values, duplicates, and invalid text.",
        "6. Clean text (lowercase, remove HTML/URLs/emails/punctuation/numbers, etc.).",
        "7. Tokenize → remove stopwords → lemmatize.",
        "8. Create `clean_text` and compute NLP features.",
        "9. Verify, save, reload, and report.",
        "",
        "## 🎯 Expected Output",
        "",
        "- Merged labeled dataset with a `clean_text` column.",
        "- NLP feature columns (`word_count`, `char_count`, `sentence_count`, `avg_word_length`).",
        "- Processed dataset: `data/processed/fake_news_dataset.csv`.",
        "- Preprocessing report: `outputs/reports/preprocessing_report.txt`.",
    ]),

    # ==================================================================
    # STEP 2 — Import Libraries
    # ==================================================================
    cell_md([
        "## Step 2 — Import Libraries",
        "",
        "### Why this step is required",
        "",
        "We need a consistent set of libraries for data manipulation (`pandas`,",
        "`numpy`), text processing (`re`, `string`, `nltk`), filesystem-safe",
        "paths (`pathlib`), and suppressing non-critical warnings (`warnings`).",
        "",
        "### What it does",
        "",
        "Imports every library used throughout the notebook and verifies the",
        "Python version.",
        "",
        "### Expected output",
        "",
        "A confirmation message listing the Python version and all imported",
        "libraries.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 2: Import Libraries",
        "# ================================================",
        "",
        "import warnings",
        "warnings.filterwarnings('ignore')",
        "",
        "import re",
        "import string",
        "import sys",
        "from pathlib import Path",
        "",
        "import numpy as np",
        "import pandas as pd",
        "",
        "import nltk",
        "from nltk.corpus import stopwords",
        "from nltk.tokenize import word_tokenize, sent_tokenize",
        "from nltk.stem import WordNetLemmatizer",
        "",
        "print(f'Python : {sys.version.split()[0]}')",
        "print(f'Pandas : {pd.__version__}')",
        "print(f'NumPy  : {np.__version__}')",
        "print(f'NLTK   : {nltk.__version__}')",
        "print('\\nAll libraries imported successfully.')",
    ]),

    # ==================================================================
    # STEP 3 — Download NLTK Resources
    # ==================================================================
    cell_md([
        "## Step 3 — Download Required NLTK Resources",
        "",
        "### Why this step is required",
        "",
        "NLTK relies on external corpora and models for tokenization",
        "(`punkt`), stopword lists (`stopwords`), and lemmatization",
        "(`wordnet` + `omw-1.4`). These must be present before use.",
        "",
        "### What it does",
        "",
        "Checks whether each resource is already available and downloads only",
        "the missing ones, so the notebook is fully reproducible on a fresh",
        "environment.",
        "",
        "### Expected output",
        "",
        "A status line for each NLTK resource (already available / downloaded).",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 3: Download Required NLTK Resources",
        "# ================================================",
        "",
        "REQUIRED_NLTK_RESOURCES = [",
        "    'punkt',",
        "    'punkt_tab',",  # required for punkt tokenizer on newer NLTK
        "    'stopwords',",
        "    'wordnet',",
        "    'omw-1.4',",
        "]",
        "",
        "def ensure_nltk_resources(resources: list[str]) -> None:",
        "    \"\"\"Download missing NLTK resources in-place.\"\"\"",
        "    for resource in resources:",
        "        try:",
        "            nltk.data.find(f'tokenizers/{resource}')",
        "        except LookupError:",
        "            try:",
        "                nltk.data.find(f'corpora/{resource}')",
        "            except LookupError:",
        "                print(f'  Downloading {resource}...')",
        "                nltk.download(resource, quiet=True)",
        "            else:",
        "                print(f'  {resource}: already available')",
        "        else:",
        "            print(f'  {resource}: already available')",
        "",
        "",
        "ensure_nltk_resources(REQUIRED_NLTK_RESOURCES)",
        "print('\\nAll NLTK resources ready.')",
    ]),

    # ==================================================================
    # STEP 4 — Load Datasets
    # ==================================================================
    cell_md([
        "## Step 4 — Load Fake.csv and True.csv",
        "",
        "### Why this step is required",
        "",
        "We must understand the raw data before transforming it: its size,",
        "column names, data types, and content shape how we clean and merge.",
        "",
        "### What it does",
        "",
        "Defines relative paths with `pathlib.Path`, loads both CSVs with",
        "`pandas`, and prints the shape, columns, head, tail, and `info()`",
        "summary for each dataset.",
        "",
        "### Expected output",
        "",
        "Two inspection blocks — one per file — showing row/column counts,",
        "sample rows, and non-null data-type information.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 4: Load Datasets",
        "# ================================================",
        "",
        "# Project-relative paths (notebooks/ -> project root)",
        "PROJECT_ROOT = Path('..').resolve()",
        "RAW_DATA_DIR = PROJECT_ROOT / 'data' / 'raw'",
        "PROCESSED_DATA_DIR = PROJECT_ROOT / 'data' / 'processed'",
        "REPORTS_DIR = PROJECT_ROOT / 'outputs' / 'reports'",
        "",
        "FAKE_PATH = RAW_DATA_DIR / 'Fake.csv'",
        "TRUE_PATH = RAW_DATA_DIR / 'True.csv'",
        "",
        "PROCESSED_CSV = PROCESSED_DATA_DIR / 'fake_news_dataset.csv'",
        "REPORT_TXT = REPORTS_DIR / 'preprocessing_report.txt'",
        "",
        "# Ensure output directories exist",
        "PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)",
        "REPORTS_DIR.mkdir(parents=True, exist_ok=True)",
        "",
        "print(f'Project root : {PROJECT_ROOT}')",
        "print(f'Fake.csv     : {FAKE_PATH}')",
        "print(f'True.csv     : {TRUE_PATH}')",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 4b: Inspect Fake.csv",
        "# ================================================",
        "",
        "df_fake = pd.read_csv(FAKE_PATH)",
        "",
        "print('=' * 70)",
        "print('FAKE NEWS DATASET (Fake.csv)')",
        "print('=' * 70)",
        "print(f'Shape: {df_fake.shape[0]:,} rows x {df_fake.shape[1]} columns')",
        "print(f'Columns: {list(df_fake.columns)}')",
        "",
        "print('\\n--- Head (first 5 rows) ---')",
        "df_fake.head()",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 4c: Inspect Fake.csv (tail + info)",
        "# ================================================",
        "",
        "print('--- Tail (last 5 rows) ---')",
        "df_fake.tail()",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 4d: Fake.csv info",
        "# ================================================",
        "",
        "df_fake.info()",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 4e: Inspect True.csv",
        "# ================================================",
        "",
        "df_true = pd.read_csv(TRUE_PATH)",
        "",
        "print('=' * 70)",
        "print('TRUE NEWS DATASET (True.csv)')",
        "print('=' * 70)",
        "print(f'Shape: {df_true.shape[0]:,} rows x {df_true.shape[1]} columns')",
        "print(f'Columns: {list(df_true.columns)}')",
        "",
        "print('\\n--- Head (first 5 rows) ---')",
        "df_true.head()",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 4f: Inspect True.csv (tail + info)",
        "# ================================================",
        "",
        "print('--- Tail (last 5 rows) ---')",
        "df_true.tail()",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 4g: True.csv info",
        "# ================================================",
        "",
        "df_true.info()",
    ]),

    # ==================================================================
    # STEP 5 — Add Labels
    # ==================================================================
    cell_md([
        "## Step 5 — Add Labels",
        "",
        "### Why this step is required",
        "",
        "Supervised ML needs a target variable. We encode the article type as a",
        "binary label so a classifier can learn to distinguish fake from true",
        "news.",
        "",
        "### What it does",
        "",
        "Creates a `label` column in each DataFrame: `Fake.csv` → `0`,",
        "`True.csv` → `1`.",
        "",
        "### Expected output",
        "",
        "A `label` column appended to each raw DataFrame.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 5: Add Labels",
        "# ================================================",
        "",
        "# Fake news -> 0, True news -> 1",
        "df_fake['label'] = 0",
        "df_true['label'] = 1",
        "",
        "print('Label added to Fake.csv  -> label = 0 (Fake)')",
        "print('Label added to True.csv  -> label = 1 (True)')",
        "",
        "print(f'\\nFake.csv label counts:',",
        "      f'  {df_fake[\"label\"].value_counts().to_dict()}')",
        "print(f'True.csv label counts:',",
        "      f'  {df_true[\"label\"].value_counts().to_dict()}')",
    ]),

    # ==================================================================
    # STEP 6 — Merge, Shuffle, Reset Index
    # ==================================================================
    cell_md([
        "## Step 6 — Merge, Shuffle, and Reset Index",
        "",
        "### Why this step is required",
        "",
        "Combining both files creates the full training corpus. Shuffling",
        "removes the ordering bias (all fake rows first), and resetting the",
        "index produces a clean sequential index after the shuffle.",
        "",
        "### What it does",
        "",
        "Concatenates the two labeled DataFrames, shuffles with a fixed random",
        "seed for reproducibility, and resets the index.",
        "",
        "### Expected output",
        "",
        "A single merged DataFrame with roughly `44,898` rows and a fresh",
        "sequential index.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 6: Merge, Shuffle, Reset Index",
        "# ================================================",
        "",
        "df = pd.concat([df_fake, df_true], axis=0, ignore_index=True)",
        "",
        "# Shuffle with fixed seed for reproducibility",
        "df = df.sample(frac=1.0, random_state=42).reset_index(drop=True)",
        "",
        "print(f'Merged dataset: {df.shape[0]:,} rows x {df.shape[1]} columns')",
        "print('Shuffled and index reset.')",
    ]),

    # ==================================================================
    # STEP 7 — Merged Shape & Class Distribution
    # ==================================================================
    cell_md([
        "## Step 7 — Merged Shape and Class Distribution",
        "",
        "### Why this step is required",
        "",
        "Before cleaning we verify the merged size and check whether the two",
        "classes are balanced. Class balance affects how we interpret accuracy",
        "later and whether any rebalancing is needed.",
        "",
        "### What it does",
        "",
        "Prints the merged shape and the count/percentage of each label.",
        "",
        "### Expected output",
        "",
        "The merged shape and a label distribution table (counts + percentages).",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 7: Merged Shape & Class Distribution",
        "# ================================================",
        "",
        "print(f'Merged shape: {df.shape[0]:,} rows x {df.shape[1]} columns')",
        "",
        "print('\\nClass distribution:')",
        "class_dist = df['label'].value_counts().sort_index()",
        "class_pct = df['label'].value_counts(normalize=True).sort_index() * 100",
        "",
        "dist_df = pd.DataFrame({",
        "    'Count': class_dist,",
        "    'Percentage': class_pct.round(2),",
        "})",
        "dist_df.index = ['Fake (0)', 'True (1)']",
        "dist_df.index.name = 'Label'",
        "display(dist_df)",
    ]),

    # ==================================================================
    # STEP 8 — Missing / Duplicate / Empty Checks
    # ==================================================================
    cell_md([
        "## Step 8 — Missing Values, Duplicates, Empty Text, Empty Title",
        "",
        "### Why this step is required",
        "",
        "Raw text data often contains missing cells, fully duplicated rows, or",
        "blank `title`/`text` fields. Detecting these before cleaning avoids",
        "silent data loss and downstream errors.",
        "",
        "### What it does",
        "",
        "Reports the total missing values, count of duplicate rows, and counts",
        "of empty/whitespace-only `text` and `title` entries.",
        "",
        "### Expected output",
        "",
        "A summary of data-quality issues in the merged dataset.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 8: Quality Checks (missing/duplicates/empty)",
        "# ================================================",
        "",
        "def is_blank(series: pd.Series) -> pd.Series:",
        "    \"\"\"Return True where the series is null or whitespace-only.\"\"\"",
        "    return series.isna() | series.astype(str).str.strip().eq('')",
        "",
        "",
        "print('=' * 70)",
        "print('DATA QUALITY CHECK (BEFORE CLEANING)')",
        "print('=' * 70)",
        "",
        "missing_total = int(df.isna().sum().sum())",
        "duplicates_total = int(df.duplicated().sum())",
        "empty_text = int(is_blank(df['text']).sum())",
        "empty_title = int(is_blank(df['title']).sum())",
        "",
        "print(f'  Missing values (total)          : {missing_total:,}')",
        "print(f'  Duplicate rows                  : {duplicates_total:,}')",
        "print(f'  Empty/blank text                : {empty_text:,}')",
        "print(f'  Empty/blank title               : {empty_title:,}')",
        "",
        "print('\\nMissing values per column:')",
        "print(df.isna().sum().to_string())",
    ]),

    # ==================================================================
    # STEP 9 — Handle Missing / Duplicates / Invalid Text
    # ==================================================================
    cell_md([
        "## Step 9 — Handle Missing Values, Duplicates, and Invalid Text",
        "",
        "### Why this step is required",
        "",
        "Machine learning models cannot consume missing or duplicated rows, and",
        "blank text produces meaningless cleaned documents. Removing or fixing",
        "these issues yields a clean, model-ready dataset.",
        "",
        "### What it does",
        "",
        "- Converts all text fields to strings and strips surrounding whitespace.",
        "- Drops rows with blank `title` or blank `text`.",
        "- Drops fully duplicated rows (keeping the first occurrence).",
        "- Reports exactly how many rows were removed at each stage.",
        "",
        "### Expected output",
        "",
        "A cleaned merged DataFrame with no missing text, no blank titles/text,",
        "and no exact duplicate rows.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 9: Handle Missing / Duplicates / Invalid Text",
        "# ================================================",
        "",
        "before_rows = len(df)",
        "",
        "# 1. Coerce text columns to string and strip whitespace",
        "for col in ['title', 'text', 'subject', 'date']:",
        "    df[col] = df[col].astype(str).str.strip()",
        "",
        "# 2. Drop rows with blank title or blank text",
        "df = df[~is_blank(df['title'])].copy()",
        "df = df[~is_blank(df['text'])].copy()",
        "",
        "# 3. Drop exact duplicate rows",
        "df = df.drop_duplicates().reset_index(drop=True)",
        "",
        "after_rows = len(df)",
        "print(f'Rows before cleaning : {before_rows:,}')",
        "print(f'Rows after cleaning  : {after_rows:,}')",
        "print(f'Rows removed         : {before_rows - after_rows:,}')",
        "",
        "print(f'\\nRemaining missing values: {int(df.isna().sum().sum()):,}')",
        "print(f'Remaining duplicates    : {int(df.duplicated().sum()):,}')",
    ]),

    # ==================================================================
    # STEP 10 — Complete NLP Cleaning
    # ==================================================================
    cell_md([
        "## Step 10 — Complete NLP Cleaning",
        "",
        "### Why this step is required",
        "",
        "Raw news text is noisy: it contains HTML, URLs, email addresses,",
        "punctuation, numbers, special characters, and non-ASCII symbols. These",
        "add noise to vector representations and rarely help classification.",
        "Normalizing the text reduces the vocabulary size and improves model",
        "performance.",
        "",
        "### What it does",
        "",
        "Defines a reusable `clean_text()` function that applies, in order:",
        "",
        "1. Lowercasing.",
        "2. Removing HTML tags.",
        "3. Removing URLs.",
        "4. Removing email addresses.",
        "5. Removing punctuation.",
        "6. Removing numbers.",
        "7. Removing special characters.",
        "8. Removing non-ASCII characters.",
        "9. Removing extra whitespace.",
        "",
        "### Expected output",
        "",
        "A clean, normalized text string for every article.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 10: Complete NLP Cleaning",
        "# ================================================",
        "",
        "# Regex patterns (compiled once for speed)",
        "_HTML_TAG_RE = re.compile(r'<[^>]+>')",
        "_URL_RE = re.compile(r'http\\S+|www\\.\\S+')",
        "_EMAIL_RE = re.compile(r'\\S+@\\S+\\.\\S+')",
        "_PUNCT_RE = re.compile(r'[' + re.escape(string.punctuation) + r']')",
        "_DIGIT_RE = re.compile(r'\\d+')",
        "_SPECIAL_RE = re.compile(r'[^a-zA-Z\\s]')",
        "_MULTI_SPACE_RE = re.compile(r'\\s+')",
        "_NON_ASCII_RE = re.compile(r'[^\\x00-\\x7F]+')",
        "",
        "",
        "def clean_text(text: str) -> str:",
        "    \"\"\"Normalize raw article text into clean, lowercase ASCII text.\"\"\"",
        "    if not isinstance(text, str):",
        "        return ''",
        "",
        "    # 1. Convert to lowercase",
        "    text = text.lower()",
        "",
        "    # 2. Remove HTML tags",
        "    text = _HTML_TAG_RE.sub(' ', text)",
        "",
        "    # 3. Remove URLs",
        "    text = _URL_RE.sub(' ', text)",
        "",
        "    # 4. Remove email addresses",
        "    text = _EMAIL_RE.sub(' ', text)",
        "",
        "    # 5. Remove punctuation",
        "    text = _PUNCT_RE.sub(' ', text)",
        "",
        "    # 6. Remove numbers",
        "    text = _DIGIT_RE.sub(' ', text)",
        "",
        "    # 7. Remove special characters (anything not a letter/space)",
        "    text = _SPECIAL_RE.sub(' ', text)",
        "",
        "    # 8. Remove non-ASCII characters",
        "    text = _NON_ASCII_RE.sub(' ', text)",
        "",
        "    # 9. Remove extra whitespace",
        "    text = _MULTI_SPACE_RE.sub(' ', text).strip()",
        "",
        "    return text",
        "",
        "",
        "# Quick sanity check",
        "sample = '<p>Breaking NEWS! Read http://example.com today\\n' \\",
        "         'email me at foo@bar.com 12345 #MAGA!!!</p>'",
        "print('Before:', sample)",
        "print('After :', clean_text(sample))",
    ]),

    # ==================================================================
    # STEP 11 — Tokenization
    # ==================================================================
    cell_md([
        "## Step 11 — Tokenization",
        "",
        "### Why this step is required",
        "",
        "Tokenization splits text into individual words (tokens), the atomic",
        "units used for stopword removal, lemmatization, and later TF-IDF",
        "vectorization.",
        "",
        "### What it does",
        "",
        "Uses NLTK's `word_tokenize` to convert each cleaned article into a",
        "list of word tokens.",
        "",
        "### Expected output",
        "",
        "A list of word tokens for each article.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 11: Tokenization",
        "# ================================================",
        "",
        "def tokenize(text: str) -> list[str]:",
        "    \"\"\"Tokenize cleaned text into a list of word tokens.\"\"\"",
        "    if not text or not isinstance(text, str):",
        "        return []",
        "    return word_tokenize(text)",
        "",
        "",
        "tokens_sample = tokenize(clean_text(df.loc[0, 'text']))",
        "print(f'Sample tokens ({len(tokens_sample)}):')",
        "print(tokens_sample[:25])",
    ]),

    # ==================================================================
    # STEP 12 — Stopword Removal
    # ==================================================================
    cell_md([
        "## Step 12 — Stopword Removal",
        "",
        "### Why this step is required",
        "",
        "High-frequency stopwords (e.g., \"the\", \"and\", \"is\") carry little",
        "discriminative signal and inflate the vocabulary. Removing them",
        "focuses the model on meaningful content words.",
        "",
        "**Important:** we keep the negation words `not`, `no`, and `never`",
        "because they strongly affect sentiment and meaning in news text.",
        "",
        "### What it does",
        "",
        "Builds an English stopword set, removes the protected negation words,",
        "and filters tokens to exclude remaining stopwords and single-character",
        "tokens.",
        "",
        "### Expected output",
        "",
        "A token list with stopwords removed but negation words preserved.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 12: Stopword Removal",
        "# ================================================",
        "",
        "# Negation words that must be preserved",
        "NEGATION_WORDS = {'not', 'no', 'never'}",
        "",
        "# Build the stopword set once",
        "_ENGLISH_STOPWORDS = set(stopwords.words('english')) - NEGATION_WORDS",
        "",
        "",
        "def remove_stopwords(tokens: list[str]) -> list[str]:",
        "    \"\"\"Remove stopwords while keeping negation words and short words.\"\"\"",
        "    return [",
        "        token for token in tokens",
        "        if token not in _ENGLISH_STOPWORDS and len(token) > 1",
        "    ]",
        "",
        "",
        "print(f'English stopwords loaded (excluding negations): {len(_ENGLISH_STOPWORDS):,}')",
        "print(f'Protected negation words: {sorted(NEGATION_WORDS)}')",
    ]),

    # ==================================================================
    # STEP 13 — Lemmatization
    # ==================================================================
    cell_md([
        "## Step 13 — Lemmatization",
        "",
        "### Why this step is required",
        "",
        "Lemmatization reduces words to their dictionary base form (e.g.,",
        "“running” → “run”). This collapses inflectional variants into one",
        "feature, shrinking the vocabulary and improving generalization.",
        "",
        "### What it does",
        "",
        "Uses NLTK's `WordNetLemmatizer` to lemmatize each token after",
        "stopword removal.",
        "",
        "### Expected output",
        "",
        "A list of lemmatized tokens ready to be joined into `clean_text`.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 13: Lemmatization",
        "# ================================================",
        "",
        "_LEMMATIZER = WordNetLemmatizer()",
        "",
        "",
        "def lemmatize(tokens: list[str]) -> list[str]:",
        "    \"\"\"Lemmatize a list of word tokens to their base forms.\"\"\"",
        "    return [_LEMMATIZER.lemmatize(token) for token in tokens]",
        "",
        "",
        "# Demonstrate lemmatization on a tiny example",
        "demo_tokens = ['running', 'cars', 'better', 'went', 'studies']",
        "print('Before:', demo_tokens)",
        "print('After :', lemmatize(demo_tokens))",
    ]),

    # ==================================================================
    # STEP 14 — Create clean_text Column
    # ==================================================================
    cell_md([
        "## Step 14 — Create the `clean_text` Column",
        "",
        "### Why this step is required",
        "",
        "The pipeline (clean → tokenize → remove stopwords → lemmatize) must be",
        "applied to every article. Storing the result in a dedicated",
        "`clean_text` column keeps the original `title`/`text` untouched for",
        "inspection and reproducibility.",
        "",
        "### What it does",
        "",
        "Applies the full preprocessing pipeline to each row's `text` column",
        "and stores the joined, lemmatized output in `clean_text`. Rows whose",
        "cleaned text becomes empty (no meaningful content remained after",
        "cleaning) are removed, because they carry no signal for the model.",
        "",
        "### Expected output",
        "",
        "A `clean_text` column containing the preprocessed article text, with",
        "empty cleaned documents removed.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 14: Create clean_text Column",
        "# ================================================",
        "",
        "def preprocess_article(text: str) -> str:",
        "    \"\"\"Full pipeline: clean -> tokenize -> remove stopwords -> lemmatize.\"\"\"",
        "    cleaned = clean_text(text)",
        "    tokens = tokenize(cleaned)",
        "    tokens = remove_stopwords(tokens)",
        "    tokens = lemmatize(tokens)",
        "    return ' '.join(tokens)",
        "",
        "",
        "df['clean_text'] = df['text'].apply(preprocess_article)",
        "",
        "rows_before_clean = len(df)",
        "",
        "# Drop rows whose cleaned text is empty (no meaningful content)",
        "df = df[~is_blank(df['clean_text'])].copy().reset_index(drop=True)",
        "",
        "rows_removed_empty = rows_before_clean - len(df)",
        "print(f'clean_text created for {rows_before_clean:,} rows.')",
        "print(f'Removed {rows_removed_empty:,} rows with empty clean_text.')",
        "df[['title', 'text', 'clean_text']].head(3)",
    ]),

    # ==================================================================
    # STEP 15 — Compute NLP Features
    # ==================================================================
    cell_md([
        "## Step 15 — Compute Additional NLP Features",
        "",
        "### Why this step is required",
        "",
        "Beyond raw text, numeric features (word/character/sentence counts and",
        "average word length) give models useful signals about article length",
        "and density, and can help detect anomalies.",
        "",
        "### What it does",
        "",
        "Adds four engineered columns computed from the cleaned text:",
        "",
        "| Column                | Description                    |",
        "|-----------------------|--------------------------------|",
        "| `word_count`          | Number of words                |",
        "| `char_count`          | Number of characters           |",
        "| `sentence_count`      | Number of sentences            |",
        "| `avg_word_length`     | Mean characters per word       |",
        "",
        "### Expected output",
        "",
        "Four new numeric columns plus a preview of the enhanced dataset.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 15: Compute Additional NLP Features",
        "# ================================================",
        "",
        "def compute_word_count(text: str) -> int:",
        "    \"\"\"Count words in a text string.\"\"\"",
        "    return len(str(text).split())",
        "",
        "",
        "def compute_char_count(text: str) -> int:",
        "    \"\"\"Count characters in a text string.\"\"\"",
        "    return len(str(text))",
        "",
        "",
        "def compute_sentence_count(text: str) -> int:",
        "    \"\"\"Count sentences using NLTK's sentence tokenizer.\"\"\"",
        "    return len(sent_tokenize(str(text)))",
        "",
        "",
        "def compute_avg_word_length(text: str) -> float:",
        "    \"\"\"Average word length (chars per word), 0 if no words.\"\"\"",
        "    words = str(text).split()",
        "    if not words:",
        "        return 0.0",
        "    return round(sum(len(word) for word in words) / len(words), 2)",
        "",
        "",
        "df['word_count'] = df['clean_text'].apply(compute_word_count)",
        "df['char_count'] = df['clean_text'].apply(compute_char_count)",
        "df['sentence_count'] = df['clean_text'].apply(compute_sentence_count)",
        "df['avg_word_length'] = df['clean_text'].apply(compute_avg_word_length)",
        "",
        "print('NLP features added: word_count, char_count, sentence_count, avg_word_length')",
        "df[['clean_text', 'word_count', 'char_count', 'sentence_count', 'avg_word_length']].head(5)",
    ]),

    # ==================================================================
    # STEP 16 — Verify Preprocessing
    # ==================================================================
    cell_md([
        "## Step 16 — Verify Preprocessing (Original → Clean)",
        "",
        "### Why this step is required",
        "",
        "We must visually confirm the pipeline works on real articles before",
        "saving. Spot-checking several examples shows how raw text is",
        "transformed and catches any unexpected behaviour.",
        "",
        "### What it does",
        "",
        "Prints a side-by-side comparison of the original `text` and the",
        "processed `clean_text` for multiple sample articles.",
        "",
        "### Expected output",
        "",
        "A readable original → clean comparison table for several rows.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 16: Verify Preprocessing",
        "# ================================================",
        "",
        "examples = df.sample(3, random_state=7)",
        "",
        "for idx, row in examples.iterrows():",
        "    print('=' * 80)",
        "    print(f\"Row {idx}  |  Label: {'Fake' if row['label'] == 0 else 'True'}\")",
        "    print('-' * 80)",
        "    print('ORIGINAL TEXT:')",
        "    print(str(row['text'])[:500])",
        "    print('\\nCLEAN TEXT:')",
        "    print(str(row['clean_text'])[:500])",
        "    print()",
    ]),

    # ==================================================================
    # STEP 17 — Quality Checks
    # ==================================================================
    cell_md([
        "## Step 17 — Quality Checks",
        "",
        "### Why this step is required",
        "",
        "Before exporting we assert the dataset meets minimum quality gates:",
        "no missing values, no duplicates, no empty cleaned text, and a",
        "balanced label distribution. This prevents silently shipping a",
        "corrupt dataset to later modules.",
        "",
        "### What it does",
        "",
        "Runs automated assertions and prints a summary of each quality gate.",
        "",
        "### Expected output",
        "",
        "All checks pass and a confirmation summary is printed.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 17: Quality Checks",
        "# ================================================",
        "",
        "print('=' * 70)",
        "print('FINAL QUALITY CHECKS')",
        "print('=' * 70)",
        "",
        "checks = {",
        "    'No missing values': int(df.isna().sum().sum()) == 0,",
        "    'No duplicate rows': int(df.duplicated().sum()) == 0,",
        "    'No empty clean_text': int(is_blank(df['clean_text']).sum()) == 0,",
        "    'Balanced labels': df['label'].value_counts().min() > 0.4 * len(df),",
        "}",
        "",
        "for name, passed in checks.items():",
        "    status = 'PASS' if passed else 'FAIL'",
        "    print(f'  [{status}] {name}')",
        "",
        "assert all(checks.values()), 'One or more quality checks failed!'",
        "print('\\n✅ All quality checks passed — dataset is model-ready.')",
    ]),

    # ==================================================================
    # STEP 18 — Save Processed Dataset
    # ==================================================================
    cell_md([
        "## Step 18 — Save the Processed Dataset",
        "",
        "### Why this step is required",
        "",
        "Persisting the cleaned dataset to CSV makes it available to later",
        "modules (EDA, model training) without re-running the entire",
        "preprocessing pipeline.",
        "",
        "### What it does",
        "",
        "Saves the processed DataFrame to `data/processed/fake_news_dataset.csv`",
        "using `utf-8` encoding and `index=False`.",
        "",
        "### Expected output",
        "",
        "A CSV file written to `data/processed/fake_news_dataset.csv`.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 18: Save Processed Dataset",
        "# ================================================",
        "",
        "df.to_csv(PROCESSED_CSV, index=False, encoding='utf-8')",
        "",
        "print(f'Processed dataset saved to: {PROCESSED_CSV}')",
        "print(f'Rows x Columns: {df.shape[0]:,} x {df.shape[1]}')",
    ]),

    # ==================================================================
    # STEP 19 — Reload and Verify
    # ==================================================================
    cell_md([
        "## Step 19 — Reload and Verify the Saved Dataset",
        "",
        "### Why this step is required",
        "",
        "Reloading the CSV from disk verifies the file is well-formed and",
        "matches the in-memory DataFrame — a critical reproducibility check.",
        "",
        "### What it does",
        "",
        "Reads the saved CSV back with `pandas`, then prints its shape, column",
        "names, and data types.",
        "",
        "### Expected output",
        "",
        "A confirmation that the reloaded dataset matches expectations.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 19: Reload and Verify",
        "# ================================================",
        "",
        "df_reloaded = pd.read_csv(PROCESSED_CSV)",
        "",
        "print('Reloaded dataset from disk:')",
        "print(f'Shape       : {df_reloaded.shape[0]:,} rows x {df_reloaded.shape[1]} columns')",
        "print(f'Columns     : {list(df_reloaded.columns)}')",
        "print(f'Data types  :')",
        "print(df_reloaded.dtypes.to_string())",
        "",
        "assert df_reloaded.shape == df.shape, 'Reloaded shape mismatch!'",
        "print('\\n✅ Reloaded dataset matches the in-memory DataFrame.')",
    ]),

    # ==================================================================
    # STEP 20 — Preprocessing Report
    # ==================================================================
    cell_md([
        "## Step 20 — Generate the Preprocessing Report",
        "",
        "### Why this step is required",
        "",
        "A concise text report documents the data cleaning summary for",
        "stakeholders and later modules: how many rows were removed, the final",
        "vocabulary size, average text length, and label distribution.",
        "",
        "### What it does",
        "",
        "Computes key metrics from the raw and cleaned DataFrames and writes",
        "them to `outputs/reports/preprocessing_report.txt`.",
        "",
        "### Expected output",
        "",
        "A human-readable `.txt` report saved to `outputs/reports/`.",
    ]),
    cell_code([
        "# ================================================",
        "# STEP 20: Generate Preprocessing Report",
        "# ================================================",
        "",
        "def build_vocabulary(texts: pd.Series) -> set[str]:",
        "    \"\"\"Build a set of all unique words across the given texts.\"\"\"",
        "    vocab: set[str] = set()",
        "    for text in texts.astype(str):",
        "        vocab.update(str(text).split())",
        "    return vocab",
        "",
        "",
        "original_rows = len(df_fake) + len(df_true)",
        "final_rows = len(df)",
        "duplicates_removed = duplicates_total",
        "missing_removed = missing_total",
        "vocab_size = len(build_vocabulary(df['clean_text']))",
        "avg_text_length = round(df['clean_text'].str.len().mean(), 2)",
        "",
        "label_dist = df['label'].value_counts().sort_index().to_dict()",
        "",
        "report_lines = [",
        "    '=' * 60,",
        "    'AI BASED FAKE NEWS DETECTION TOOL',",
        "    'MODULE 2 — DATA PREPROCESSING REPORT',",
        "    '=' * 60,",
        "    '',",
        "    f'Original rows (Fake + True) : {original_rows:,}',",
        "    f'Final rows (after cleaning) : {final_rows:,}',",
        "    f'Rows removed                : {original_rows - final_rows:,}',",
        "    f'Duplicates removed          : {duplicates_removed:,}',",
        "    f'Missing values removed      : {missing_removed:,}',",
        "    f'Vocabulary size             : {vocab_size:,}',",
        "    f'Average text length (chars) : {avg_text_length}',",
        "    '',",
        "    'Label distribution:',",
        "    f'  Fake (0) : {label_dist.get(0, 0):,}',",
        "    f'  True (1) : {label_dist.get(1, 0):,}',",
        "    '',",
        "    f'Processed dataset : {PROCESSED_CSV}',",
        "    f'Report generated  : data_preprocessing.ipynb (Module 2)',",
        "    '=' * 60,",
        "]",
        "",
        "REPORT_TXT.write_text('\\n'.join(report_lines), encoding='utf-8')",
        "",
        "print('\\n'.join(report_lines))",
        "print(f'\\n✅ Report saved to: {REPORT_TXT}')",
    ]),
]


# ----------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------


def main() -> None:
    """Build and write the notebook JSON to disk."""
    notebook = make_notebook(cells)
    notebook_path = Path(__file__).resolve().parent / 'data_preprocessing.ipynb'

    with notebook_path.open('w', encoding='utf-8') as fh:
        json.dump(notebook, fh, indent=1, ensure_ascii=False)

    n_cells = len(notebook['cells'])
    print(f'✅ Notebook generated: {notebook_path}')
    print(f'   Cells: {n_cells} ({sum(c["cell_type"] == "code" for c in notebook["cells"])} code, '
          f'{sum(c["cell_type"] == "markdown" for c in notebook["cells"])} markdown)')


if __name__ == '__main__':
    main()

