#!/usr/bin/env python3
"""Generate the Module 3 EDA notebook programmatically.

This script builds ``notebooks/eda.ipynb`` for the AI Based Fake News
Detection Tool. The notebook covers ONLY Exploratory Data Analysis:
loading the processed dataset, target/subject/date analysis, text-length
distributions, word clouds, n-gram frequencies, correlation, outliers,
statistical comparison, insight extraction, chart saving, and an EDA
report. No TF-IDF / model training / prediction is included (later
modules).

Usage:
    python notebooks/write_eda_notebook.py
"""

import json
from pathlib import Path

# ----------------------------------------------------------------------
# Notebook builders
# ----------------------------------------------------------------------


def cell_code(source_lines: list[str]) -> dict:
    """Create a code cell from a list of source lines."""
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [s + "\n" for s in source_lines],
    }


def cell_md(source_lines: list[str]) -> dict:
    """Create a markdown cell from a list of source lines."""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [s + "\n" for s in source_lines],
    }


def make_notebook(cells: list[dict]) -> dict:
    """Assemble a Jupyter notebook JSON document."""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.12.0",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 4,
    }


# ----------------------------------------------------------------------
# Markdown cells
# ----------------------------------------------------------------------

md_overview = cell_md([
    "# AI Based Fake News Detection Tool",
    "",
    "## Module 3 — Exploratory Data Analysis (EDA)",
    "",
    "### CodeVedX AI/ML Internship — Project 3",
    "",
    "---",
    "",
    "## 📌 Project Overview",
    "",
    "This notebook performs **Exploratory Data Analysis (EDA)** on the",
    "processed dataset produced in **Module 2**",
    "(`data/processed/fake_news_dataset.csv`). The goal is to understand",
    "the structure, distributions, and relationships inside the data",
    "before training machine-learning models in Module 4.",
    "",
    "## 🎯 Purpose of EDA",
    "",
    "- Verify dataset integrity (missing values, duplicates, memory).",
    "- Analyse the **target variable** (`label`: Fake=0 / True=1).",
    "- Explore **text-length features** and **average word length**.",
    "- Study **subjects/categories** and **publication dates**.",
    "- Visualise frequent words, **bigrams** and **trigrams**.",
    "- Inspect **correlations** and **outliers** among numeric features.",
    "- Extract **statistical insights** that guide feature engineering",
    "  and model selection.",
    "",
    "## 🗂️ Dataset Summary",
    "",
    "| Property              | Value                                   |",
    "|-----------------------|-----------------------------------------|",
    "| Source                | `data/processed/fake_news_dataset.csv`  |",
    "| Rows                  | 43,971                                  |",
    "| Columns               | 10                                      |",
    "| Features              | `title`, `text`, `subject`, `date`, `label`, `clean_text`, `word_count`, `char_count`, `sentence_count`, `avg_word_length` |",
    "| Target                | `label` (0 = Fake, 1 = True)            |",
    "",
    "## 📤 Expected Outputs",
    "",
    "- Professional visualisations saved under `outputs/charts/`.",
    "- An EDA report saved to `outputs/reports/eda_report.txt`.",
    "- Actionable insights for **Module 4 (Model Training)**.",
])

md_imports = cell_md([
    "## Step 2 — Import Libraries",
    "",
    "### Why this step is required",
    "",
    "A consistent set of libraries is needed for data manipulation",
    "(`pandas`, `numpy`), plotting (`matplotlib`, `seaborn`, `wordcloud`),",
    "word frequencies (`collections.Counter`), filesystem-safe paths",
    "(`pathlib`), and suppressing non-critical warnings (`warnings`).",
    "",
    "### What it does",
    "",
    "Imports all libraries used throughout the notebook and prints the",
    "Python version.",
    "",
    "### Expected output",
    "",
    "A confirmation message listing the Python version and all imported",
    "libraries.",
])

md_load = cell_md([
    "## Step 3 — Load Dataset",
    "",
    "### Why this step is required",
    "",
    "We must load and inspect the processed dataset before any analysis.",
    "Checking the shape, columns, data types, head and tail gives us a",
    "first sense of the data.",
    "",
    "### What it does",
    "",
    "Loads `data/processed/fake_news_dataset.csv` with `pandas` and prints",
    "the shape, columns, data types, first rows and last rows.",
    "",
    "### Expected output",
    "",
    "An overview of the dataset size, schema and a few sample rows.",
])

md_summary = cell_md([
    "## Step 4 — Dataset Summary",
    "",
    "### Why this step is required",
    "",
    "Descriptive statistics and data-quality metrics reveal the range,",
    "central tendency, missing values, duplicate rows and memory usage of",
    "the dataset — critical context for every later analysis.",
    "",
    "### What it does",
    "",
    "Displays `describe()`, total missing values, duplicate row count and",
    "the approximate memory footprint.",
    "",
    "### Expected output",
    "",
    "A numeric summary table plus data-quality counts.",
])

md_target = cell_md([
    "## Step 5 — Target Variable Analysis",
    "",
    "### Why this step is required",
    "",
    "The target `label` (Fake=0, True=1) drives all supervised learning.",
    "Checking class balance tells us whether accuracy is a reliable",
    "metric and whether rebalancing may be needed.",
    "",
    "### What it does",
    "",
    "Computes count and percentage per class, then renders a bar chart and",
    "a pie chart. Both charts are saved.",
    "",
    "### Expected output",
    "",
    "A label distribution table and two saved charts",
    "(`label_distribution.png`, `label_distribution_pie.png`).",
])

md_text_length = cell_md([
    "## Step 6 — Text Length Analysis",
    "",
    "### Why this step is required",
    "",
    "Article length features (`word_count`, `char_count`, `sentence_count`)",
    "can differ between fake and real news. Understanding their",
    "distributions helps with feature engineering and anomaly detection.",
    "",
    "### What it does",
    "",
    "Creates histograms, boxplots, violin plots and density plots for each",
    "of the three length features, split by `label`. All are saved.",
    "",
    "### Expected output",
    "",
    "Twelve saved charts (histograms, boxplots, violin plots, density",
    "plots for word/char/sentence counts).",
])

md_avg_word_length = cell_md([
    "## Step 7 — Average Word Length Analysis",
    "",
    "### Why this step is required",
    "",
    "Average word length is a proxy for vocabulary sophistication. Fake",
    "news may use different wording patterns than real news, making this a",
    "potentially useful feature.",
    "",
    "### What it does",
    "",
    "Renders a histogram and a boxplot of `avg_word_length` split by",
    "`label`, and saves both.",
    "",
    "### Expected output",
    "",
    "Two saved charts (`avg_word_length_histogram.png`,",
    "`avg_word_length_boxplot.png`).",
])

md_subject = cell_md([
    "## Step 8 — Subject Analysis",
    "",
    "### Why this step is required",
    "",
    "The `subject` column groups articles by topic. Understanding the",
    "distribution reveals which categories dominate and how subject",
    "relates to the target label.",
    "",
    "### What it does",
    "",
    "Computes subject counts, renders a count plot and a pie chart, and",
    "prints the top categories per label.",
    "",
    "### Expected output",
    "",
    "Saved charts (`subject_countplot.png`, `subject_pie.png`) plus a",
    "printed top-subjects table.",
])

md_date = cell_md([
    "## Step 9 — Publication Date Analysis",
    "",
    "### Why this step is required",
    "",
    "Publication dates can reveal temporal patterns (spikes around news",
    "events). Analysing years and months helps detect trends in article",
    "volume.",
    "",
    "### What it does",
    "",
    "Parses the `date` column into a datetime, extracts publication year",
    "and month, then renders a time-series plot and bar charts. Invalid or",
    "unparsable dates are counted and reported.",
    "",
    "### Expected output",
    "",
    "Saved charts (`publication_year_timeseries.png`,",
    "`publication_month_bar.png`, `publication_year_bar.png`).",
])

md_wordcloud = cell_md([
    "## Step 10 — WordClouds",
    "",
    "### Why this step is required",
    "",
    "Word clouds give an immediate visual summary of the most frequent",
    "words in each class. Comparing fake vs real word clouds can reveal",
    "thematic differences in vocabulary.",
    "",
    "### What it does",
    "",
    "Generates one high-resolution word cloud for fake news (`label=0`)",
    "and one for real news (`label=1`), and saves both as PNG files.",
    "",
    "### Expected output",
    "",
    "Two saved charts (`wordcloud_fake.png`, `wordcloud_real.png`).",
])

md_common_words = cell_md([
    "## Step 11 — Most Common Words",
    "",
    "### Why this step is required",
    "",
    "Counting the most frequent words per class highlights the dominant",
    "vocabulary of fake vs real news. This guides stopword choices and",
    "feature selection.",
    "",
    "### What it does",
    "",
    "Builds a `Counter` of words per label and displays the top 30 words",
    "for fake and real news as horizontal bar charts.",
    "",
    "### Expected output",
    "",
    "Two saved charts (`top_words_fake.png`, `top_words_real.png`).",
])

md_bigrams = cell_md([
    "## Step 12 — Most Common Bigrams",
    "",
    "### Why this step is required",
    "",
    "Bigrams (two-word sequences) capture short phrases that single words",
    "miss — for example, \"white house\" or \"fake news\". They improve",
    "interpretability and can boost model features.",
    "",
    "### What it does",
    "",
    "Extracts and counts bigrams per label, then visualises the top 20",
    "for fake and real news.",
    "",
    "### Expected output",
    "",
    "Two saved charts (`top_bigrams_fake.png`, `top_bigrams_real.png`).",
])

md_trigrams = cell_md([
    "## Step 13 — Most Common Trigrams",
    "",
    "### Why this step is required",
    "",
    "Trigrams (three-word sequences) capture even richer phrases and",
    "context. They can reveal recurring narrative patterns in each class.",
    "",
    "### What it does",
    "",
    "Extracts and counts trigrams per label, then visualises the top 20",
    "for fake and real news.",
    "",
    "### Expected output",
    "",
    "Two saved charts (`top_trigrams_fake.png`, `top_trigrams_real.png`).",
])

md_correlation = cell_md([
    "## Step 14 — Correlation Analysis",
    "",
    "### Why this step is required",
    "",
    "Correlations among numeric features reveal redundancy (e.g.,",
    "`word_count` and `char_count` are usually strongly correlated) and",
    "inform which features to keep or drop before modelling.",
    "",
    "### What it does",
    "",
    "Computes the Pearson correlation matrix of the numeric features and",
    "renders a heatmap. The heatmap is saved.",
    "",
    "### Expected output",
    "",
    "A correlation table and a saved chart",
    "(`correlation_heatmap.png`).",
])

md_outliers = cell_md([
    "## Step 15 — Outlier Analysis",
    "",
    "### Why this step is required",
    "",
    "Outliers in `word_count`, `char_count`, `sentence_count` and",
    "`avg_word_length` can skew statistics and hurt model performance.",
    "The IQR method quantifies how many extreme values exist.",
    "",
    "### What it does",
    "",
    "Applies the IQR rule to each numeric feature, reports outlier counts,",
    "and renders boxplots (already produced in Step 6) plus a dedicated",
    "outlier boxplot chart.",
    "",
    "### Expected output",
    "",
    "A printed outlier summary and a saved chart",
    "(`outlier_boxplot.png`).",
])

md_stats = cell_md([
    "## Step 16 — Statistical Summary (Fake vs Real)",
    "",
    "### Why this step is required",
    "",
    "Comparing average word count, character count and sentence count",
    "between fake and real articles reveals whether article length differs",
    "by class — a useful signal for the classifier.",
    "",
    "### What it does",
    "",
    "Groups the data by `label` and prints mean/median values of the",
    "length features.",
    "",
    "### Expected output",
    "",
    "A side-by-side statistical comparison table.",
])

md_insights = cell_md([
    "## Step 17 — Interesting Insights",
    "",
    "### Why this step is required",
    "",
    "Automatically extracting observations turns raw statistics into",
    "actionable knowledge for stakeholders and the modelling team.",
    "",
    "### What it does",
    "",
    "Prints a set of computed insights: average fake/real article length,",
    "most common subject, vocabulary comparison and label balance.",
    "",
    "### Expected output",
    "",
    "A printed bullet list of key findings.",
])

md_save_charts = cell_md([
    "## Step 18 — Save Every Chart",
    "",
    "### Why this step is required",
    "",
    "All figures must be persisted so they can be shared, included in",
    "reports, and reused. Centralised saving ensures consistent filenames",
    "and locations.",
    "",
    "### What it does",
    "",
    "This step is executed incrementally throughout the notebook — every",
    "chart is saved to `outputs/charts/` at the point it is created. This",
    "cell verifies that all expected chart files exist.",
    "",
    "### Expected output",
    "",
    "A listing of every chart file in `outputs/charts/`.",
])

md_report = cell_md([
    "## Step 19 — Generate the EDA Report",
    "",
    "### Why this step is required",
    "",
    "A concise text report summarises the EDA findings for later modules",
    "and stakeholders: dataset size, label/subject distributions, average",
    "text lengths, frequent subjects, key findings and recommendations",
    "for model training.",
    "",
    "### What it does",
    "",
    "Computes all summary metrics and writes them to",
    "`outputs/reports/eda_report.txt`.",
    "",
    "### Expected output",
    "",
    "A human-readable `.txt` report saved to `outputs/reports/`.",
])

md_validation = cell_md([
    "## Step 20 — Notebook Validation",
    "",
    "### Why this step is required",
    "",
    "Before finishing Module 3 we must confirm the notebook runs end to",
    "end, all charts are saved and the EDA report exists — with no",
    "exceptions.",
    "",
    "### What it does",
    "",
    "Checks that `outputs/charts/` contains the expected PNG files and",
    "that `outputs/reports/eda_report.txt` exists, then prints a final",
    "summary.",
    "",
    "### Expected output",
    "",
    "A validation summary confirming all outputs are present.",
])

# ----------------------------------------------------------------------
# Code cell source strings
# ----------------------------------------------------------------------

code_imports = [
    "# ================================================",
    "# STEP 2: Import Libraries",
    "# ================================================",
    "",
    "import sys",
    "import warnings",
    "from collections import Counter",
    "from pathlib import Path",
    "",
    "import matplotlib",
    "import matplotlib.pyplot as plt",
    "import numpy as np",
    "import pandas as pd",
    "import seaborn as sns",
    "from wordcloud import WordCloud",
    "",
    "warnings.filterwarnings('ignore')",
    "",
    "# Consistent, professional colour palette",
    "PALETTE = {'Fake': '#e74c3c', 'True': '#2ecc71'}",
    "",
    "sns.set_theme(style='whitegrid', palette='deep')",
    "plt.rcParams.update({",
    "    'figure.dpi': 120,",
    "    'savefig.dpi': 150,",
    "    'font.size': 10,",
    "    'axes.titlesize': 13,",
    "    'axes.labelsize': 11,",
    "    'legend.fontsize': 9,",
    "    'figure.autolayout': True,",
    "})",
    "",
    "print(f'Python   : {sys.version.split()[0]}')",
    "print(f'Pandas   : {pd.__version__}')",
    "print(f'NumPy    : {np.__version__}')",
    "print(f'Matplotlib: {matplotlib.__version__}')",
    "print(f'Seaborn  : {sns.__version__}')",
    "print('\\nAll libraries imported successfully.')",
]

code_setup = [
    "# ================================================",
    "# STEP 3 (setup): Paths & Output Directories",
    "# ================================================",
    "",
    "# Project-relative paths (notebooks/ -> project root)",
    "PROJECT_ROOT = Path('..').resolve()",
    "PROCESSED_CSV = PROJECT_ROOT / 'data' / 'processed' / 'fake_news_dataset.csv'",
    "CHARTS_DIR = PROJECT_ROOT / 'outputs' / 'charts'",
    "REPORTS_DIR = PROJECT_ROOT / 'outputs' / 'reports'",
    "EDA_REPORT = REPORTS_DIR / 'eda_report.txt'",
    "",
    "# Ensure output directories exist",
    "CHARTS_DIR.mkdir(parents=True, exist_ok=True)",
    "REPORTS_DIR.mkdir(parents=True, exist_ok=True)",
    "",
    "print(f'Project root : {PROJECT_ROOT}')",
    "print(f'Dataset      : {PROCESSED_CSV}')",
    "print(f'Charts dir   : {CHARTS_DIR}')",
    "print(f'Report dir   : {REPORTS_DIR}')",
]

code_load = [
    "# ================================================",
    "# STEP 3: Load Dataset",
    "# ================================================",
    "",
    "try:",
    "    df = pd.read_csv(PROCESSED_CSV, encoding='utf-8')",
    "    print('Dataset loaded successfully.')",
    "except FileNotFoundError as exc:",
    "    raise SystemExit(f'Dataset not found: {PROCESSED_CSV}') from exc",
    "except pd.errors.EmptyDataError as exc:",
    "    raise SystemExit(f'Dataset is empty: {PROCESSED_CSV}') from exc",
    "",
    "print(f'Shape: {df.shape[0]:,} rows x {df.shape[1]} columns')",
    "print(f'\\nColumns: {list(df.columns)}')",
    "",
    "print('\\n--- Data types ---')",
    "print(df.dtypes.to_string())",
    "",
    "print('\\n--- Head (first 5 rows) ---')",
    "df.head()",
]

code_load_tail = [
    "# ================================================",
    "# STEP 3b: Tail",
    "# ================================================",
    "",
    "print('--- Tail (last 5 rows) ---')",
    "df.tail()",
]

code_summary = [
    "# ================================================",
    "# STEP 4: Dataset Summary",
    "# ================================================",
    "",
    "print('--- describe() ---')",
    "display(df.describe())",
    "",
    "print('\\n--- Missing values per column ---')",
    "print(df.isna().sum().to_string())",
    "",
    "print('\\n--- Missing values (total) ---')",
    "print(f'{int(df.isna().sum().sum()):,}')",
    "",
    "print('\\n--- Duplicate rows ---')",
    "print(f'{int(df.duplicated().sum()):,}')",
    "",
    "print('\\n--- Memory usage ---')",
    "print(df.memory_usage(deep=True).to_string())",
    "print(f'\\nTotal memory: {df.memory_usage(deep=True).sum() / 1024 ** 2:.2f} MB')",
]

code_target = [
    "# ================================================",
    "# STEP 5: Target Variable Analysis",
    "# ================================================",
    "",
    "label_counts = df['label'].value_counts().sort_index()",
    "label_pct = df['label'].value_counts(normalize=True).sort_index() * 100",
    "",
    "label_df = pd.DataFrame({",
    "    'Count': label_counts,",
    "    'Percentage': label_pct.round(2),",
    "})",
    "label_df.index = ['Fake (0)', 'True (1)']",
    "label_df.index.name = 'Label'",
    "print('Label distribution:')",
    "display(label_df)",
    "",
    "# --- Bar chart ---",
    "fig, ax = plt.subplots(figsize=(7, 5))",
    "colors = [PALETTE['Fake'], PALETTE['True']]",
    "bars = ax.bar(['Fake', 'True'], label_counts.values, color=colors, edgecolor='black', alpha=0.85)",
    "",
    "for bar, count, pct in zip(bars, label_counts.values, label_pct.values):",
    "    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 300,",
    "            f'{count:,}\\n({pct:.1f}%)', ha='center', va='bottom', fontsize=10, fontweight='bold')",
    "",
    "ax.set_title('Label Distribution — Fake vs True News', fontweight='bold')",
    "ax.set_xlabel('Label')",
    "ax.set_ylabel('Number of Articles')",
    "ax.grid(axis='y', alpha=0.3)",
    "fig.savefig(CHARTS_DIR / 'label_distribution.png')",
    "plt.show()",
    "",
    "# --- Pie chart ---",
    "fig, ax = plt.subplots(figsize=(7, 6))",
    "ax.pie(label_counts.values, labels=['Fake', 'True'], colors=colors,",
    "       autopct='%1.1f%%', startangle=90, explode=(0.03, 0.03),",
    "       textprops={'fontsize': 11}, wedgeprops={'edgecolor': 'white', 'linewidth': 1.5})",
    "ax.set_title('Label Distribution — Pie Chart', fontweight='bold')",
    "fig.savefig(CHARTS_DIR / 'label_distribution_pie.png')",
    "plt.show()",
]

code_text_length = [
    "# ================================================",
    "# STEP 6: Text Length Analysis",
    "# ================================================",
    "",
    "LENGTH_FEATURES = ['word_count', 'char_count', 'sentence_count']",
    "",
    "def plot_length_analysis(feature: str) -> None:",
    "    \"\"\"Render histogram, boxplot, violin and density plots for a length feature.\"\"\"",
    "    fake = df[df['label'] == 0][feature]",
    "    true = df[df['label'] == 1][feature]",
    "",
    "    # 1. Histogram",
    "    fig, ax = plt.subplots(figsize=(8, 5))",
    "    ax.hist(fake, bins=50, alpha=0.6, color=PALETTE['Fake'], edgecolor='white', label='Fake')",
    "    ax.hist(true, bins=50, alpha=0.6, color=PALETTE['True'], edgecolor='white', label='True')",
    "    ax.set_title(f'{feature.replace(\"_\", \" \").title()} Distribution', fontweight='bold')",
    "    ax.set_xlabel(feature.replace('_', ' ').title())",
    "    ax.set_ylabel('Frequency')",
    "    ax.grid(axis='y', alpha=0.3)",
    "    ax.legend()",
    "    fig.savefig(CHARTS_DIR / f'text_length_histogram_{feature}.png')",
    "    plt.show()",
    "",
    "    # 2. Boxplot",
    "    fig, ax = plt.subplots(figsize=(7, 5))",
    "    sns.boxplot(data=df, x='label', y=feature, palette=[PALETTE['Fake'], PALETTE['True']], ax=ax)",
    "    ax.set_xticklabels(['Fake (0)', 'True (1)'])",
    "    ax.set_title(f'{feature.replace(\"_\", \" \").title()} Boxplot by Label', fontweight='bold')",
    "    ax.set_xlabel('Label')",
    "    ax.grid(axis='y', alpha=0.3)",
    "    fig.savefig(CHARTS_DIR / f'text_length_boxplot_{feature}.png')",
    "    plt.show()",
    "",
    "    # 3. Violin plot",
    "    fig, ax = plt.subplots(figsize=(7, 5))",
    "    sns.violinplot(data=df, x='label', y=feature, palette=[PALETTE['Fake'], PALETTE['True']], ax=ax)",
    "    ax.set_xticklabels(['Fake (0)', 'True (1)'])",
    "    ax.set_title(f'{feature.replace(\"_\", \" \").title()} Violin Plot by Label', fontweight='bold')",
    "    ax.set_xlabel('Label')",
    "    ax.grid(axis='y', alpha=0.3)",
    "    fig.savefig(CHARTS_DIR / f'text_length_violin_{feature}.png')",
    "    plt.show()",
    "",
    "    # 4. Density plot",
    "    fig, ax = plt.subplots(figsize=(8, 5))",
    "    sns.kdeplot(fake, label='Fake', color=PALETTE['Fake'], fill=True, alpha=0.3, ax=ax)",
    "    sns.kdeplot(true, label='True', color=PALETTE['True'], fill=True, alpha=0.3, ax=ax)",
    "    ax.set_title(f'{feature.replace(\"_\", \" \").title()} Density Plot by Label', fontweight='bold')",
    "    ax.set_xlabel(feature.replace('_', ' ').title())",
    "    ax.set_ylabel('Density')",
    "    ax.grid(axis='y', alpha=0.3)",
    "    ax.legend()",
    "    fig.savefig(CHARTS_DIR / f'text_length_density_{feature}.png')",
    "    plt.show()",
    "",
    "",
    "for feature in LENGTH_FEATURES:",
    "    print('=' * 70)",
    "    print(f'ANALYSING: {feature}')",
    "    print('=' * 70)",
    "    plot_length_analysis(feature)",
]

code_avg_word_length = [
    "# ================================================",
    "# STEP 7: Average Word Length Analysis",
    "# ================================================",
    "",
    "fake_awl = df[df['label'] == 0]['avg_word_length']",
    "true_awl = df[df['label'] == 1]['avg_word_length']",
    "",
    "# 1. Histogram",
    "fig, ax = plt.subplots(figsize=(8, 5))",
    "ax.hist(fake_awl, bins=40, alpha=0.6, color=PALETTE['Fake'], edgecolor='white', label='Fake')",
    "ax.hist(true_awl, bins=40, alpha=0.6, color=PALETTE['True'], edgecolor='white', label='True')",
    "ax.set_title('Average Word Length Distribution', fontweight='bold')",
    "ax.set_xlabel('Average Word Length')",
    "ax.set_ylabel('Frequency')",
    "ax.grid(axis='y', alpha=0.3)",
    "ax.legend()",
    "fig.savefig(CHARTS_DIR / 'avg_word_length_histogram.png')",
    "plt.show()",
    "",
    "# 2. Boxplot",
    "fig, ax = plt.subplots(figsize=(7, 5))",
    "sns.boxplot(data=df, x='label', y='avg_word_length',",
    "            palette=[PALETTE['Fake'], PALETTE['True']], ax=ax)",
    "ax.set_xticklabels(['Fake (0)', 'True (1)'])",
    "ax.set_title('Average Word Length Boxplot by Label', fontweight='bold')",
    "ax.set_xlabel('Label')",
    "ax.set_ylabel('Average Word Length')",
    "ax.grid(axis='y', alpha=0.3)",
    "fig.savefig(CHARTS_DIR / 'avg_word_length_boxplot.png')",
    "plt.show()",
]

code_subject = [
    "# ================================================",
    "# STEP 8: Subject Analysis",
    "# ================================================",
    "",
    "subject_counts = df['subject'].value_counts()",
    "print('Subject distribution:')",
    "display(subject_counts.to_frame('Count'))",
    "",
    "# 1. Count plot",
    "fig, ax = plt.subplots(figsize=(10, 6))",
    "order = subject_counts.index",
    "sns.countplot(data=df, y='subject', order=order, palette='viridis', ax=ax)",
    "ax.set_title('Number of Articles per Subject', fontweight='bold')",
    "ax.set_xlabel('Number of Articles')",
    "ax.set_ylabel('Subject')",
    "ax.grid(axis='x', alpha=0.3)",
    "fig.tight_layout()",
    "fig.savefig(CHARTS_DIR / 'subject_countplot.png')",
    "plt.show()",
    "",
    "# 2. Pie chart",
    "fig, ax = plt.subplots(figsize=(9, 7))",
    "ax.pie(subject_counts.values, labels=subject_counts.index, autopct='%1.1f%%',",
    "       startangle=90, textprops={'fontsize': 9}, wedgeprops={'edgecolor': 'white', 'linewidth': 1})",
    "ax.set_title('Subject Distribution — Pie Chart', fontweight='bold')",
    "fig.savefig(CHARTS_DIR / 'subject_pie.png')",
    "plt.show()",
    "",
    "# 3. Top categories per label",
    "print('\\n--- Top subjects for Fake news ---')",
    "fake_subjects = df[df['label'] == 0]['subject'].value_counts().head(5)",
    "display(fake_subjects.to_frame('Count'))",
    "print('\\n--- Top subjects for True news ---')",
    "true_subjects = df[df['label'] == 1]['subject'].value_counts().head(5)",
    "display(true_subjects.to_frame('Count'))",
]

code_date = [
    "# ================================================",
    "# STEP 9: Publication Date Analysis",
    "# ================================================",
    "",
    "def parse_date(value):",
    "    \"\"\"Parse a date string into a datetime, or NaT on failure.\"\"\"",
    "    if pd.isna(value) or not isinstance(value, str):",
    "        return pd.NaT",
    "    text = str(value).strip()",
    "    for fmt in ('%B %d, %Y', '%d-%b-%y'):",
    "        try:",
    "            return pd.to_datetime(text, format=fmt)",
    "        except (ValueError, TypeError):",
    "            continue",
    "    return pd.NaT",
    "",
    "",
    "df['date_parsed'] = df['date'].apply(parse_date)",
    "n_parsed = df['date_parsed'].notna().sum()",
    "n_failed = df['date_parsed'].isna().sum()",
    "print(f'Successfully parsed: {n_parsed:,} rows')",
    "print(f'Failed to parse     : {n_failed:,} rows')",
    "",
    "df['year'] = df['date_parsed'].dt.year",
    "df['month'] = df['date_parsed'].dt.month",
    "",
    "valid_dates = df.dropna(subset=['date_parsed']).copy()",
    "print(f'\\nDate range: {valid_dates[\"date_parsed\"].min()} to {valid_dates[\"date_parsed\"].max()}')",
    "",
    "# 1. Time series of article volume over time",
    "fig, ax = plt.subplots(figsize=(12, 5))",
    "volume = valid_dates.groupby('date_parsed').size()",
    "ax.plot(volume.index, volume.values, color='#3498db', linewidth=1.2)",
    "ax.set_title('Article Volume Over Time', fontweight='bold')",
    "ax.set_xlabel('Publication Date')",
    "ax.set_ylabel('Number of Articles')",
    "ax.grid(alpha=0.3)",
    "fig.tight_layout()",
    "fig.savefig(CHARTS_DIR / 'publication_year_timeseries.png')",
    "plt.show()",
    "",
    "# 2. Publications per month",
    "fig, ax = plt.subplots(figsize=(9, 5))",
    "monthly = valid_dates['month'].value_counts().sort_index()",
    "ax.bar(monthly.index, monthly.values, color='#9b59b6', edgecolor='black', alpha=0.85)",
    "ax.set_title('Articles per Month', fontweight='bold')",
    "ax.set_xlabel('Month')",
    "ax.set_ylabel('Number of Articles')",
    "ax.set_xticks(range(1, 13))",
    "ax.set_xticklabels(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',",
    "                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])",
    "ax.grid(axis='y', alpha=0.3)",
    "fig.savefig(CHARTS_DIR / 'publication_month_bar.png')",
    "plt.show()",
    "",
    "# 3. Publications per year",
    "fig, ax = plt.subplots(figsize=(9, 5))",
    "yearly = valid_dates['year'].value_counts().sort_index()",
    "ax.bar(yearly.index.astype(int).astype(str), yearly.values, color='#1abc9c',",
    "       edgecolor='black', alpha=0.85)",
    "ax.set_title('Articles per Year', fontweight='bold')",
    "ax.set_xlabel('Year')",
    "ax.set_ylabel('Number of Articles')",
    "ax.grid(axis='y', alpha=0.3)",
    "fig.savefig(CHARTS_DIR / 'publication_year_bar.png')",
    "plt.show()",
]

code_wordcloud = [
    "# ================================================",
    "# STEP 10: WordClouds",
    "# ================================================",
    "",
    "def generate_wordcloud(texts: pd.Series, title: str, out_path: Path) -> None:",
    "    \"\"\"Generate and save a high-resolution word cloud.\"\"\"",
    "    text = ' '.join(texts.astype(str).tolist())",
    "    wordcloud = WordCloud(width=1600, height=900, background_color='white',",
    "                          max_words=200, colormap='viridis', collocations=False,",
    "                          random_state=42).generate(text)",
    "    fig, ax = plt.subplots(figsize=(14, 8))",
    "    ax.imshow(wordcloud, interpolation='bilinear')",
    "    ax.axis('off')",
    "    ax.set_title(title, fontweight='bold', fontsize=16)",
    "    fig.tight_layout()",
    "    fig.savefig(out_path, dpi=150)",
    "    plt.show()",
    "",
    "",
    "print('Generating word cloud for FAKE news...')",
    "generate_wordcloud(df[df['label'] == 0]['clean_text'],",
    "                   'Most Frequent Words — Fake News', CHARTS_DIR / 'wordcloud_fake.png')",
    "",
    "print('Generating word cloud for REAL news...')",
    "generate_wordcloud(df[df['label'] == 1]['clean_text'],",
    "                   'Most Frequent Words — Real News', CHARTS_DIR / 'wordcloud_real.png')",
]

code_common_words = [
    "# ================================================",
    "# STEP 11: Most Common Words",
    "# ================================================",
    "",
    "def get_top_ngrams(texts: pd.Series, n: int, k: int) -> list[tuple[str, int]]:",
    "    \"\"\"Return the top-k n-grams as a list of (ngram, count) tuples.\"\"\"",
    "    counter: Counter = Counter()",
    "    for text in texts.astype(str):",
    "        tokens = str(text).split()",
    "        ngrams = zip(*[tokens[i:] for i in range(n)])",
    "        counter.update(' '.join(gram) for gram in ngrams)",
    "    return counter.most_common(k)",
    "",
    "",
    "def plot_top_ngrams(ngrams, title: str, out_path: Path, color: str) -> None:",
    "    \"\"\"Plot top n-grams as a horizontal bar chart.\"\"\"",
    "    labels = [item[0] for item in ngrams][::-1]",
    "    values = [item[1] for item in ngrams][::-1]",
    "    fig, ax = plt.subplots(figsize=(10, 8))",
    "    ax.barh(labels, values, color=color, edgecolor='black', alpha=0.85)",
    "    ax.set_title(title, fontweight='bold')",
    "    ax.set_xlabel('Frequency')",
    "    ax.grid(axis='x', alpha=0.3)",
    "    fig.tight_layout()",
    "    fig.savefig(out_path)",
    "    plt.show()",
    "",
    "",
    "top_words_fake = get_top_ngrams(df[df['label'] == 0]['clean_text'], 1, 30)",
    "top_words_true = get_top_ngrams(df[df['label'] == 1]['clean_text'], 1, 30)",
    "",
    "print('Top 30 words — FAKE news:')",
    "for word, count in top_words_fake:",
    "    print(f'  {word:<20} {count:>6,}')",
    "",
    "print('\\nTop 30 words — REAL news:')",
    "for word, count in top_words_true:",
    "    print(f'  {word:<20} {count:>6,}')",
    "",
    "plot_top_ngrams(top_words_fake, 'Top 30 Words — Fake News',",
    "                CHARTS_DIR / 'top_words_fake.png', PALETTE['Fake'])",
    "plot_top_ngrams(top_words_true, 'Top 30 Words — Real News',",
    "                CHARTS_DIR / 'top_words_real.png', PALETTE['True'])",
]

code_bigrams = [
    "# ================================================",
    "# STEP 12: Most Common Bigrams",
    "# ================================================",
    "",
    "top_bigrams_fake = get_top_ngrams(df[df['label'] == 0]['clean_text'], 2, 20)",
    "top_bigrams_true = get_top_ngrams(df[df['label'] == 1]['clean_text'], 2, 20)",
    "",
    "print('Top 20 bigrams — FAKE news:')",
    "for gram, count in top_bigrams_fake:",
    "    print(f'  {gram:<30} {count:>6,}')",
    "",
    "print('\\nTop 20 bigrams — REAL news:')",
    "for gram, count in top_bigrams_true:",
    "    print(f'  {gram:<30} {count:>6,}')",
    "",
    "plot_top_ngrams(top_bigrams_fake, 'Top 20 Bigrams — Fake News',",
    "                CHARTS_DIR / 'top_bigrams_fake.png', '#e67e22')",
    "plot_top_ngrams(top_bigrams_true, 'Top 20 Bigrams — Real News',",
    "                CHARTS_DIR / 'top_bigrams_real.png', '#16a085')",
]

code_trigrams = [
    "# ================================================",
    "# STEP 13: Most Common Trigrams",
    "# ================================================",
    "",
    "top_trigrams_fake = get_top_ngrams(df[df['label'] == 0]['clean_text'], 3, 20)",
    "top_trigrams_true = get_top_ngrams(df[df['label'] == 1]['clean_text'], 3, 20)",
    "",
    "print('Top 20 trigrams — FAKE news:')",
    "for gram, count in top_trigrams_fake:",
    "    print(f'  {gram:<40} {count:>6,}')",
    "",
    "print('\\nTop 20 trigrams — REAL news:')",
    "for gram, count in top_trigrams_true:",
    "    print(f'  {gram:<40} {count:>6,}')",
    "",
    "plot_top_ngrams(top_trigrams_fake, 'Top 20 Trigrams — Fake News',",
    "                CHARTS_DIR / 'top_trigrams_fake.png', '#c0392b')",
    "plot_top_ngrams(top_trigrams_true, 'Top 20 Trigrams — Real News',",
    "                CHARTS_DIR / 'top_trigrams_real.png', '#27ae60')",
]

code_correlation = [
    "# ================================================",
    "# STEP 14: Correlation Analysis",
    "# ================================================",
    "",
    "NUMERIC_FEATURES = ['word_count', 'char_count', 'sentence_count', 'avg_word_length']",
    "corr = df[NUMERIC_FEATURES].corr()",
    "",
    "print('Correlation matrix:')",
    "display(corr.round(3))",
    "",
    "fig, ax = plt.subplots(figsize=(8, 6))",
    "sns.heatmap(corr, annot=True, fmt='.3f', cmap='coolwarm', center=0,",
    "            linewidths=0.8, linecolor='white', square=True, ax=ax)",
    "ax.set_title('Correlation Heatmap of Numeric Features', fontweight='bold')",
    "fig.savefig(CHARTS_DIR / 'correlation_heatmap.png')",
    "plt.show()",
]

code_outliers = [
    "# ================================================",
    "# STEP 15: Outlier Analysis (IQR)",
    "# ================================================",
    "",
    "def iqr_outlier_summary(feature: str) -> tuple[int, int]:",
    "    \"\"\"Return (n_low_outliers, n_high_outliers) for a feature using the IQR rule.\"\"\"",
    "    q1 = df[feature].quantile(0.25)",
    "    q3 = df[feature].quantile(0.75)",
    "    iqr = q3 - q1",
    "    lower = q1 - 1.5 * iqr",
    "    upper = q3 + 1.5 * iqr",
    "    n_low = int((df[feature] < lower).sum())",
    "    n_high = int((df[feature] > upper).sum())",
    "    return n_low, n_high",
    "",
    "",
    "print('Outlier summary (IQR rule):')",
    "print('=' * 60)",
    "for feature in NUMERIC_FEATURES:",
    "    low, high = iqr_outlier_summary(feature)",
    "    total = low + high",
    "    pct = total / len(df) * 100",
    "    print(f'  {feature:<16} low={low:>5,}  high={high:>5,}  total={total:>6,}  ({pct:.2f}%)')",
    "",
    "# Dedicated boxplot chart",
    "fig, axes = plt.subplots(2, 2, figsize=(12, 9))",
    "for ax, feature in zip(axes.flatten(), NUMERIC_FEATURES):",
    "    sns.boxplot(data=df, x='label', y=feature, ax=ax,",
    "                palette=[PALETTE['Fake'], PALETTE['True']])",
    "    ax.set_xticklabels(['Fake', 'True'])",
    "    ax.set_title(feature.replace('_', ' ').title())",
    "    ax.set_xlabel('')",
    "fig.suptitle('Outlier Analysis — Boxplots by Label', fontweight='bold', fontsize=14)",
    "fig.tight_layout()",
    "fig.savefig(CHARTS_DIR / 'outlier_boxplot.png')",
    "plt.show()",
]

code_stats = [
    "# ================================================",
    "# STEP 16: Statistical Summary (Fake vs Real)",
    "# ================================================",
    "",
    "stats = df.groupby('label')[NUMERIC_FEATURES].agg(['mean', 'median', 'std']).round(2)",
    "stats.index = ['Fake (0)', 'True (1)']",
    "print('Statistical comparison — Fake vs Real:')",
    "display(stats)",
    "",
    "print('\\n--- Average words / chars / sentences per label ---')",
    "summary = df.groupby('label').agg({",
    "    'word_count': 'mean',",
    "    'char_count': 'mean',",
    "    'sentence_count': 'mean',",
    "    'avg_word_length': 'mean',",
    "}).round(2)",
    "summary.index = ['Fake (0)', 'True (1)']",
    "display(summary)",
]

code_insights = [
    "# ================================================",
    "# STEP 17: Interesting Insights",
    "# ================================================",
    "",
    "fake_text = df[df['label'] == 0]['clean_text']",
    "true_text = df[df['label'] == 1]['clean_text']",
    "",
    "avg_fake_words = fake_text.str.split().str.len().mean()",
    "avg_true_words = true_text.str.split().str.len().mean()",
    "avg_fake_chars = fake_text.str.len().mean()",
    "avg_true_chars = true_text.str.len().mean()",
    "",
    "most_common_subject = df['subject'].value_counts().idxmax()",
    "most_common_subject_count = df['subject'].value_counts().max()",
    "",
    "fake_vocab = set(' '.join(fake_text.astype(str)).split())",
    "true_vocab = set(' '.join(true_text.astype(str)).split())",
    "",
    "n_fake = int((df['label'] == 0).sum())",
    "n_true = int((df['label'] == 1).sum())",
    "pct_fake = n_fake / len(df) * 100",
    "pct_true = n_true / len(df) * 100",
    "",
    "insights = [",
    "    f'1. Dataset size: {len(df):,} articles.',",
    "    f'2. Label balance: Fake = {n_fake:,} ({pct_fake:.1f}%), True = {n_true:,} ({pct_true:.1f}%) — nearly balanced.',",
    "    f'3. Average fake article length: {avg_fake_words:.1f} words / {avg_fake_chars:.1f} characters.',",
    "    f'4. Average real article length: {avg_true_words:.1f} words / {avg_true_chars:.1f} characters.',",
    "    f'5. Fake news is on average {abs(avg_fake_words - avg_true_words):.1f} words {\"longer\" if avg_fake_words > avg_true_words else \"shorter\"} than real news.',",
    "    f'6. Most common subject: \"{most_common_subject}\" with {most_common_subject_count:,} articles.',",
    "    f'7. Vocabulary size — Fake: {len(fake_vocab):,} unique words; True: {len(true_vocab):,} unique words.',",
    "    f'8. Subjects are fully separated by label (each subject belongs to exactly one class).',",
    "    f'9. word_count and char_count are very strongly correlated (see heatmap), indicating redundancy.',",
    "    f'10. Several outliers exist in length features — robust scaling may help modelling.',",
    "]",
    "",
    "print('=' * 70)",
    "print('KEY INSIGHTS')",
    "print('=' * 70)",
    "for line in insights:",
    "    print(line)",
]

code_save_charts = [
    "# ================================================",
    "# STEP 18: Save Every Chart (verification)",
    "# ================================================",
    "",
    "expected_charts = [",
    "    'label_distribution.png',",
    "    'label_distribution_pie.png',",
    "    'text_length_histogram_word_count.png',",
    "    'text_length_boxplot_word_count.png',",
    "    'text_length_violin_word_count.png',",
    "    'text_length_density_word_count.png',",
    "    'text_length_histogram_char_count.png',",
    "    'text_length_boxplot_char_count.png',",
    "    'text_length_violin_char_count.png',",
    "    'text_length_density_char_count.png',",
    "    'text_length_histogram_sentence_count.png',",
    "    'text_length_boxplot_sentence_count.png',",
    "    'text_length_violin_sentence_count.png',",
    "    'text_length_density_sentence_count.png',",
    "    'avg_word_length_histogram.png',",
    "    'avg_word_length_boxplot.png',",
    "    'subject_countplot.png',",
    "    'subject_pie.png',",
    "    'publication_year_timeseries.png',",
    "    'publication_month_bar.png',",
    "    'publication_year_bar.png',",
    "    'wordcloud_fake.png',",
    "    'wordcloud_real.png',",
    "    'top_words_fake.png',",
    "    'top_words_real.png',",
    "    'top_bigrams_fake.png',",
    "    'top_bigrams_real.png',",
    "    'top_trigrams_fake.png',",
    "    'top_trigrams_real.png',",
    "    'correlation_heatmap.png',",
    "    'outlier_boxplot.png',",
    "]",
    "",
    "missing = [name for name in expected_charts if not (CHARTS_DIR / name).exists()]",
    "print(f'Expected charts: {len(expected_charts)}')",
    "print(f'Charts present : {len(expected_charts) - len(missing)}')",
    "print(f'Charts missing : {len(missing)}')",
    "",
    "if missing:",
    "    print('\\nMissing files:')",
    "    for name in missing:",
    "        print(f'  - {name}')",
    "else:",
    "    print('\\n✅ All expected charts are present.')",
    "",
    "print('\\n--- Files in outputs/charts/ ---')",
    "for path in sorted(CHARTS_DIR.glob('*.png')):",
    "    print(f'  {path.name}  ({path.stat().st_size / 1024:.1f} KB)')",
]

code_report = [
    "# ================================================",
    "# STEP 19: Generate EDA Report",
    "# ================================================",
    "",
    "def build_eda_report(df: pd.DataFrame, charts_dir: Path) -> list[str]:",
    "    \"\"\"Compose the EDA report lines.\"\"\"",
    "    # Original dataset columns (10) — date analysis adds temporary",
    "    # columns (date_parsed, year, month) that are not part of the dataset.",
    "    n_rows = len(df)",
    "    n_cols = len(df.columns) - sum(c in df.columns for c in ['date_parsed', 'year', 'month'])",
    "    n_fake = int((df['label'] == 0).sum())",
    "    n_true = int((df['label'] == 1).sum())",
    "    pct_fake = n_fake / n_rows * 100",
    "    pct_true = n_true / n_rows * 100",
    "",
    "    subject_dist = df['subject'].value_counts()",
    "    most_common_subject = subject_dist.idxmax()",
    "    most_common_subject_count = subject_dist.max()",
    "",
    "    avg_word_count = df['word_count'].mean()",
    "    avg_char_count = df['char_count'].mean()",
    "    avg_sentence_count = df['sentence_count'].mean()",
    "    avg_word_length = df['avg_word_length'].mean()",
    "",
    "    avg_fake_words = df.loc[df['label'] == 0, 'word_count'].mean()",
    "    avg_true_words = df.loc[df['label'] == 1, 'word_count'].mean()",
    "    avg_fake_chars = df.loc[df['label'] == 0, 'char_count'].mean()",
    "    avg_true_chars = df.loc[df['label'] == 1, 'char_count'].mean()",
    "",
    "    fake_vocab = set(' '.join(df.loc[df['label'] == 0, 'clean_text'].astype(str)).split())",
    "    true_vocab = set(' '.join(df.loc[df['label'] == 1, 'clean_text'].astype(str)).split())",
    "    shared_vocab = fake_vocab & true_vocab",
    "",
    "    n_charts = len(list(charts_dir.glob('*.png')))",
    "    top_subjects = ', '.join(subject_dist.head(5).index.tolist())",
    "",
    "    lines = [",
    "        '=' * 70,",
    "        'AI BASED FAKE NEWS DETECTION TOOL',",
    "        'MODULE 3 — EXPLORATORY DATA ANALYSIS (EDA) REPORT',",
    "        '=' * 70,",
    "        '',",
    "        '1. DATASET SIZE',",
    "        f'   - Rows    : {n_rows:,}',",
    "        f'   - Columns : {n_cols}',",
    "        '',",
    "        '2. LABEL DISTRIBUTION',",
    "        f'   - Fake (0): {n_fake:,} ({pct_fake:.1f}%)',",
    "        f'   - True (1): {n_true:,} ({pct_true:.1f}%)',",
    "        '',",
    "        '3. SUBJECT DISTRIBUTION',",
    "        f'   - Most frequent subject : \"{most_common_subject}\" ({most_common_subject_count:,} articles)',",
    "        f'   - Top 5 subjects        : {top_subjects}',",
    "        '',",
    "        '4. AVERAGE TEXT LENGTH',",
    "        f'   - Average word count        : {avg_word_count:.1f}',",
    "        f'   - Average character count   : {avg_char_count:.1f}',",
    "        f'   - Average sentence count    : {avg_sentence_count:.1f}',",
    "        f'   - Average word length       : {avg_word_length:.2f}',",
    "        '',",
    "        '5. FAKE vs TRUE COMPARISON',",
    "        f'   - Fake avg words : {avg_fake_words:.1f}  |  True avg words : {avg_true_words:.1f}',",
    "        f'   - Fake avg chars : {avg_fake_chars:.1f}  |  True avg chars : {avg_true_chars:.1f}',",
    "        '',",
    "        '6. VOCABULARY COMPARISON',",
    "        f'   - Fake vocabulary size : {len(fake_vocab):,}',",
    "        f'   - True vocabulary size : {len(true_vocab):,}',",
    "        f'   - Shared vocabulary    : {len(shared_vocab):,}',",
    "        '',",
    "        '7. INTERESTING FINDINGS',",
    "        '   - The dataset is nearly balanced (no heavy rebalancing required).',",
    "        '   - Subjects are fully separated by label: each subject maps to exactly one class.',",
    "        '   - Fake articles are on average longer than real articles.',",
    "        '   - word_count and char_count are strongly correlated (redundant features).',",
    "        '   - A small number of non-standard dates were handled during date parsing.',",
    "        '   - Length features contain outliers; robust scaling is advisable.',",
    "        '',",
    "        '8. RECOMMENDATIONS FOR MODEL TRAINING',",
    "        '   - Use TF-IDF on clean_text with n-gram range (1,2) or (1,3).',",
    "        '   - Consider dropping redundant numeric features (e.g., char_count).',",
    "        '   - Apply robust scaling to numeric features if they are used.',",
    "        '   - Use stratified train/test split because classes are nearly balanced.',",
    "        '   - Evaluate with accuracy, precision, recall, F1 and confusion matrix.',",
    "        '',",
    "        f'   - Charts generated   : {n_charts} PNG files in outputs/charts/',",
    "        f'   - Processed dataset  : data/processed/fake_news_dataset.csv',",
    "        f'   - Report generated   : eda.ipynb (Module 3)',",
    "        '=' * 70,",
    "    ]",
    "    return lines",
    "",
    "",
    "report_lines = build_eda_report(df, CHARTS_DIR)",
    "EDA_REPORT.write_text('\\n'.join(report_lines), encoding='utf-8')",
    "",
    "print('\\n'.join(report_lines))",
    "print(f'\\n✅ EDA report saved to: {EDA_REPORT}')",
]

code_validation = [
    "# ================================================",
    "# STEP 20: Notebook Validation",
    "# ================================================",
    "",
    "expected_charts = [",
    "    'label_distribution.png',",
    "    'label_distribution_pie.png',",
    "    'text_length_histogram_word_count.png',",
    "    'text_length_boxplot_word_count.png',",
    "    'text_length_violin_word_count.png',",
    "    'text_length_density_word_count.png',",
    "    'text_length_histogram_char_count.png',",
    "    'text_length_boxplot_char_count.png',",
    "    'text_length_violin_char_count.png',",
    "    'text_length_density_char_count.png',",
    "    'text_length_histogram_sentence_count.png',",
    "    'text_length_boxplot_sentence_count.png',",
    "    'text_length_violin_sentence_count.png',",
    "    'text_length_density_sentence_count.png',",
    "    'avg_word_length_histogram.png',",
    "    'avg_word_length_boxplot.png',",
    "    'subject_countplot.png',",
    "    'subject_pie.png',",
    "    'publication_year_timeseries.png',",
    "    'publication_month_bar.png',",
    "    'publication_year_bar.png',",
    "    'wordcloud_fake.png',",
    "    'wordcloud_real.png',",
    "    'top_words_fake.png',",
    "    'top_words_real.png',",
    "    'top_bigrams_fake.png',",
    "    'top_bigrams_real.png',",
    "    'top_trigrams_fake.png',",
    "    'top_trigrams_real.png',",
    "    'correlation_heatmap.png',",
    "    'outlier_boxplot.png',",
    "]",
    "",
    "missing_charts = [name for name in expected_charts if not (CHARTS_DIR / name).exists()]",
    "report_exists = EDA_REPORT.exists()",
    "",
    "print('=' * 70)",
    "print('FINAL VALIDATION')",
    "print('=' * 70)",
    "print(f'  Charts present  : {len(expected_charts) - len(missing_charts)}/{len(expected_charts)}')",
    "print(f'  EDA report exists: {report_exists}')",
    "",
    "if missing_charts:",
    "    print('  Missing charts:')",
    "    for name in missing_charts:",
    "        print(f'    - {name}')",
    "",
    "assert not missing_charts, 'One or more charts are missing!'",
    "assert report_exists, 'EDA report was not generated!'",
    "",
    "print('\\n✅ Module 3 EDA validation passed — all outputs are present.')",
    "print('   Notebook executed successfully.')",
]

# ----------------------------------------------------------------------
# Assemble the notebook
# ----------------------------------------------------------------------

cells = [
    md_overview,
    md_imports,
    cell_code(code_imports),
    cell_code(code_setup),
    md_load,
    cell_code(code_load),
    cell_code(code_load_tail),
    md_summary,
    cell_code(code_summary),
    md_target,
    cell_code(code_target),
    md_text_length,
    cell_code(code_text_length),
    md_avg_word_length,
    cell_code(code_avg_word_length),
    md_subject,
    cell_code(code_subject),
    md_date,
    cell_code(code_date),
    md_wordcloud,
    cell_code(code_wordcloud),
    md_common_words,
    cell_code(code_common_words),
    md_bigrams,
    cell_code(code_bigrams),
    md_trigrams,
    cell_code(code_trigrams),
    md_correlation,
    cell_code(code_correlation),
    md_outliers,
    cell_code(code_outliers),
    md_stats,
    cell_code(code_stats),
    md_insights,
    cell_code(code_insights),
    md_save_charts,
    cell_code(code_save_charts),
    md_report,
    cell_code(code_report),
    md_validation,
    cell_code(code_validation),
]


def main() -> None:
    """Build and write the EDA notebook JSON to disk."""
    notebook = make_notebook(cells)
    notebook_path = Path(__file__).resolve().parent / "eda.ipynb"

    with notebook_path.open("w", encoding="utf-8") as fh:
        json.dump(notebook, fh, indent=1, ensure_ascii=False)

    n_cells = len(notebook["cells"])
    n_code = sum(c["cell_type"] == "code" for c in notebook["cells"])
    n_md = sum(c["cell_type"] == "markdown" for c in notebook["cells"])
    print(f"✅ Notebook generated: {notebook_path}")
    print(f"   Cells: {n_cells} ({n_code} code, {n_md} markdown)")


if __name__ == "__main__":
    main()

